{{- if .Values.icn.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "icn.fullname" . }}-pvc
  labels:
    {{- include "icn.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.icn.persistence.size }}
{{- end }}
