apiVersion: v1
kind: Secret
metadata:
  name: {{ include "icn.fullname" . }}-secret
  labels:
    {{- include "icn.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.icn.secrets.jwtSecret | quote }}
