[package]
name = "federation-lifecycle"
version = "0.1.0"
edition = "2021"
description = "Federation merge and split lifecycle management for the Intercooperative Network"
license = "MIT OR Apache-2.0"

[dependencies]
# Core dependencies
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }

# ICN dependencies
icn-common = { path = "../icn-common" }
icn-identity = { path = "../icn-identity" }
icn-federation = { path = "../icn-federation" }
icn-economics = { path = "../icn-economics" }
icn-dag = { path = "../icn-dag" }
icn-core-vm = { path = "../icn-core-vm" }
icn-governance-kernel = { path = "../icn-governance-kernel" }

# CBOR and CID for content addressing
cid = { workspace = true }
multihash = { workspace = true }
serde_ipld_dagcbor = { workspace = true }

# Other utilities
chrono = { workspace = true }
uuid = { workspace = true }
sha2 = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
tokio-test = "0.4" 