[package]
name = "icn-dag"
version = "0.1.0"
edition = "2021"
description = "DAG objects, Merkle anchoring, and Lineage for the ICN Runtime"

[dependencies]
icn-common = { path = "../common" }
icn-identity = { path = "../identity" }
icn-models = { path = "../models" }
icn-storage = { path = "../storage" }

# Workspace dependencies
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
clap = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
base64 = { version = "0.21", features = ["std"] }
sha2 = { workspace = true }
anyhow = { workspace = true }

# IPLD/Network dependencies
cid = { workspace = true }
libipld = { workspace = true }

# Other dependencies
lru = "0.12"
hashbrown = "0.14"

[dev-dependencies]
tempfile = "3.9.0"
rand = "0.8.5"
