[package]
name = "wallet-ffi"
version = "0.1.0"
edition = "2021"
description = "Foreign Function Interface for the ICN Wallet Core"

[lib]
name = "wallet_ffi"
crate-type = ["cdylib", "staticlib", "lib"]

[dependencies]
wallet-core = { path = "../wallet-core" }
wallet-agent = { path = "../wallet-agent", optional = true }
wallet-sync = { path = "../wallet-sync" }
wallet-types = { path = "../wallet-types" }
uniffi = { version = "0.23.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.28", features = ["full"] }
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1.0"
async-trait = "0.1"
log = "0.4"
once_cell = "1.18"

[features]
default = []
agent = ["wallet-agent"]

[build-dependencies]
uniffi_build = { version = "0.23.0", features = ["builtin-bindgen"] }

[dev-dependencies]
tokio-test = "0.4" 