version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/backend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/crates/icn-consensus"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/crates/icn-core"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/crates/icn-crypto"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/crates/icn-p2p"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/crates/icn-runtime"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/crates/icn-storage"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/crates/icn-types"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "security"
    versioning-strategy:
      increase: "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci-cd"
      - "dependencies"
    groups:
      actions:
        patterns:
          - "*"
