global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'icn-runtime'
    scrape_interval: 5s
    static_configs:
      - targets: ['icn-runtime:9090']

  - job_name: 'agoranet'
    scrape_interval: 10s
    static_configs:
      - targets: ['agoranet:3000']
    metrics_path: '/metrics'

  - job_name: 'wallet-agent'
    scrape_interval: 10s
    static_configs:
      - targets: ['wallet-agent:8000']
    metrics_path: '/metrics' 