#!/usr/bin/env python3
"""
Regulatory Compliance Linter - CI Script

Scans public API surfaces (gateway, SDKs, UI) for terminology that could
trigger financial-services classification (MSB/custodial). ICN is
communications infrastructure, not a payment processor — the surface
language must reflect this.

See docs/dev/language-guide.md for the full terminology guide and rationale.

Usage:
    python3 .github/scripts/compliance_linter.py [--repo-root PATH]

Exit codes:
    0: No violations detected
    1: Violations detected
    2: Script error

Tracking Issue: #1312 (regulatory compliance CI gate)
"""

import argparse
import os
import re
import sys
from dataclasses import dataclass, field
from typing import List, Tuple

# ---------------------------------------------------------------------------
# Forbidden patterns
# ---------------------------------------------------------------------------
# Each entry: (compiled regex, human-readable description, note about exceptions)
# Patterns are case-insensitive and match identifiers/strings, not comments.

FORBIDDEN_PATTERNS: List[Tuple[re.Pattern, str]] = [
    # payment / pay — MSB trigger
    (
        re.compile(r"\bCreatePaymentRequest\b", re.IGNORECASE),
        "CreatePaymentRequest → use RecordTransferRequest",
    ),
    (
        re.compile(r"\bPaymentCreated\b", re.IGNORECASE),
        "PaymentCreated → use SettlementCreated",
    ),
    (
        re.compile(r'\bpayments?[:/]', re.IGNORECASE),
        "payment endpoint/scope → use settlement",
    ),
    # hosted_wallet — custodial trigger
    (
        re.compile(r"\bhosted_wallet\b", re.IGNORECASE),
        "hosted_wallet → use account",
    ),
    # send_funds / transfer_funds — operator-mediated transfer
    (
        re.compile(r"\bsend[_\s]funds\b", re.IGNORECASE),
        "send_funds → use create_settlement or record_transfer",
    ),
    (
        re.compile(r"\btransfer[_\s]funds\b", re.IGNORECASE),
        "transfer_funds → use propose_transfer",
    ),
    # exchange_rate in public API fields
    (
        re.compile(r"\bexchange_rate\b", re.IGNORECASE),
        "exchange_rate in public API → omit; use governance proposals",
    ),
    (
        re.compile(r"\bexchangeRate\b"),
        "exchangeRate in public API → omit; use governance proposals",
    ),
    # fiat_equivalent — convertibility trigger
    (
        re.compile(r"\bfiat_equivalent\b", re.IGNORECASE),
        "fiat_equivalent → remove (implies convertibility)",
    ),
    (
        re.compile(r"\bfiatEquivalent\b"),
        "fiatEquivalent → remove (implies convertibility)",
    ),
    # redemption / redeem — convertibility trigger
    (
        re.compile(r"\bredeem\b", re.IGNORECASE),
        "redeem → describe the actual action instead",
    ),
    (
        re.compile(r"\bredemption\b", re.IGNORECASE),
        "redemption → describe the actual action instead",
    ),
]


# ---------------------------------------------------------------------------
# Scan scope
# ---------------------------------------------------------------------------
# Paths relative to repo root. Only public API surfaces — not internal
# ledger code, FX oracle adapters, or test fixtures.

SCAN_GLOBS = [
    # Gateway public API
    "icn/crates/icn-gateway/src/models.rs",
    "icn/crates/icn-gateway/src/api/**/*.rs",
    # TypeScript SDK (not node_modules or generated)
    "sdk/typescript/src/**/*.ts",
    # React Native SDK
    "sdk/react-native/src/**/*.ts",
    # Pilot UI (flat structure — JS, HTML, CSS)
    "web/pilot-ui/**/*.js",
    "web/pilot-ui/**/*.html",
    "web/pilot-ui/**/*.css",
]

# Files/directories to always skip (even if matched by globs)
SKIP_PATTERNS = [
    "node_modules/",
    "/generated/",
    "api-types.ts",  # auto-generated by openapi-typescript
    ".test.ts",
    ".test.js",
    "/tests/",
    "test-api.html",
]

# Filename patterns that are themselves evidence of legacy naming
# (e.g., recurring_payments.rs) — we flag the filename, not just contents
FORBIDDEN_FILENAMES = [
    (re.compile(r"recurring_payments"), "recurring_payments → rename to recurring_settlements"),
]


@dataclass
class Violation:
    file: str
    line: int
    text: str
    rule: str


@dataclass
class LintResult:
    violations: List[Violation] = field(default_factory=list)
    files_scanned: int = 0


def should_skip(filepath: str) -> bool:
    """Check if a file should be excluded from scanning."""
    for pattern in SKIP_PATTERNS:
        if pattern in filepath:
            return True
    return False


def is_comment_line(line: str, filepath: str) -> bool:
    """Heuristic: skip lines that are comments (not strings or code)."""
    stripped = line.lstrip()
    if filepath.endswith((".rs",)):
        return stripped.startswith("//") or stripped.startswith("///") or stripped.startswith("//!")
    if filepath.endswith((".ts", ".js")):
        return stripped.startswith("//") or stripped.startswith("*") or stripped.startswith("/*")
    if filepath.endswith(".html"):
        return stripped.startswith("<!--")
    return False


def scan_file(filepath: str, abs_path: str) -> List[Violation]:
    """Scan a single file for forbidden patterns."""
    violations = []

    # Check filename itself
    basename = os.path.basename(filepath)
    for pattern, rule in FORBIDDEN_FILENAMES:
        if pattern.search(basename):
            violations.append(Violation(file=filepath, line=0, text=f"filename: {basename}", rule=rule))

    try:
        with open(abs_path, "r", encoding="utf-8", errors="replace") as f:
            for line_num, line in enumerate(f, start=1):
                # Skip comment-only lines to reduce false positives
                if is_comment_line(line, filepath):
                    continue

                for pattern, rule in FORBIDDEN_PATTERNS:
                    if pattern.search(line):
                        violations.append(
                            Violation(
                                file=filepath,
                                line=line_num,
                                text=line.rstrip()[:120],
                                rule=rule,
                            )
                        )
    except OSError as e:
        print(f"Warning: could not read {filepath}: {e}", file=sys.stderr)

    return violations


def expand_globs(repo_root: str) -> List[Tuple[str, str]]:
    """Expand SCAN_GLOBS into (relative_path, absolute_path) pairs."""
    import glob as globmod

    results = []
    for pattern in SCAN_GLOBS:
        abs_pattern = os.path.join(repo_root, pattern)
        for abs_path in globmod.glob(abs_pattern, recursive=True):
            if not os.path.isfile(abs_path):
                continue
            rel_path = os.path.relpath(abs_path, repo_root)
            if not should_skip(rel_path):
                results.append((rel_path, abs_path))
    return sorted(set(results))


def run_lint(repo_root: str) -> LintResult:
    """Run the compliance linter across all in-scope files."""
    result = LintResult()
    files = expand_globs(repo_root)
    result.files_scanned = len(files)

    for rel_path, abs_path in files:
        violations = scan_file(rel_path, abs_path)
        result.violations.extend(violations)

    return result


def main() -> int:
    parser = argparse.ArgumentParser(description="ICN Regulatory Compliance Linter")
    parser.add_argument(
        "--repo-root",
        default=os.getcwd(),
        help="Repository root directory (default: cwd)",
    )
    args = parser.parse_args()

    repo_root = os.path.abspath(args.repo_root)

    print("=" * 70)
    print("Regulatory Compliance Linter")
    print("Forbidden terminology in public API surfaces")
    print("=" * 70)
    print()
    print(f"Repo root: {repo_root}")
    print(f"Reference: docs/dev/language-guide.md")
    print()

    result = run_lint(repo_root)

    print(f"Scanned {result.files_scanned} files")
    print()

    if not result.violations:
        print("✅ No compliance violations detected!")
        print()
        print("All public API surfaces use approved terminology.")
        return 0

    # Group violations by file
    by_file: dict[str, List[Violation]] = {}
    for v in result.violations:
        by_file.setdefault(v.file, []).append(v)

    print(f"❌ {len(result.violations)} COMPLIANCE VIOLATION(S) DETECTED:")
    print()

    for filepath in sorted(by_file.keys()):
        violations = by_file[filepath]
        print(f"  {filepath}:")
        for v in violations:
            if v.line > 0:
                print(f"    L{v.line}: {v.rule}")
                print(f"           {v.text}")
            else:
                print(f"    {v.rule}")
                print(f"           {v.text}")
        print()

    print("To fix: see docs/dev/language-guide.md for approved alternatives.")
    print("These terms trigger financial-services classification risk.")
    print()

    return 1


if __name__ == "__main__":
    sys.exit(main())
