version: 2
snapshot:
  widths:
    - 375  # Mobile
    - 768  # Tablet
    - 1280 # Desktop
  minHeight: 1024
  enableJavaScript: true
  percyCSS: |
    /* Hide dynamic content that changes between snapshots */
    [data-percy-hidden] {
      visibility: hidden;
    }
discovery:
  allowedHostnames: []  # Add any external domains needed for testing
  disallowedHostnames: []  # Add any domains to exclude
static:
  baseUrl: /
  files: "frontend/build/**"