[workspace]
members = [
  "crates/icn-types",
  "crates/icn-core",
  "crates/icn-runtime"
]

[workspace.dependencies]
# Internal crates
icn-types = { path = "crates/icn-types" }
icn-core = { path = "crates/icn-core" }
icn-runtime = { path = "crates/icn-runtime" }

# External dependencies
tokio = { version = "1.30", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
warp = "0.3"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio"] }
thiserror = "1.0"
chrono = { version = "0.4", features = ["serde"] }
async-trait = "0.1"
futures = "0.3"
tracing = "0.1"
sha2 = "0.10"
rayon = "1.7"
lazy_static = "1.4"
serde_json = "1.0"

[package]
name = "icn"
version = "0.1.0"
description = "Inter-Cooperative Network - A platform for cooperative resource sharing and governance"
edition = "2021"

[features]
default = ["basic"]
basic = []
federation = ["dep:tokio", "dep:async-trait"]
advanced-governance = ["dep:parity-scale-codec"]
monitoring = ["dep:prometheus"]

[dependencies]
icn-types = { workspace = true }
tokio = { workspace = true, optional = true }
async-trait = { workspace = true, optional = true }
parity-scale-codec = { version = "3.0", optional = true }
prometheus = { version = "0.13", optional = true }
serde = { workspace = true }

[lib]
name = "icn_lib"
path = "src/lib.rs"

[[bin]]
name = "icn_bin"
path = "src/main.rs"
