[workspace]
members = [
    "backend",
    "crates/icn-core",
    "crates/icn-consensus",
    "crates/icn-crypto",
    "crates/icn-dsl",
    "crates/icn-federation",
    "crates/icn-p2p",
    "crates/icn-resource",
    "crates/icn-runtime",
    "crates/icn-storage",
    "crates/icn-types"
]

[workspace.dependencies]
tokio = { version = "1.30", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
warp = "0.3"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio"] }
