[workspace]
resolver = "2"
members = [
    "agoranet",
    "runtime",
    "runtime/cli",
    "wallet",
    "runtime/crates/*",
    "wallet/crates/*"
]
exclude = [
    "agoranet",
    "wallet/crates/wallet-ffi"
]

[workspace.dependencies]
# Common dependencies
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
futures = "0.3"
clap = { version = "4.4", features = ["derive"] }

# Network and storage
libp2p = "0.53"
multihash = { version = "0.16.3", features = ["sha2"] }
cid = { version = "0.10.1", features = ["serde"] }

# IPLD related dependencies
# Note: libipld is officially deprecated in favor of ipld-core, but we'll keep both for compatibility
libipld = { version = "0.16", features = ["derive"] }
libipld-core = "0.13.1"
# For DAG-CBOR serialization - using the recommended libraries
serde_ipld_dagcbor = "0.4"
ipld-core = "0.3"

# Identity and security
# Using ssi 0.7 with features that are available
ssi = { version = "0.7", features = ["ed25519", "rsa"] }
did-method-key = "0.2"

# Runtime-specific dependencies
wasmer = "3.1"
wasmer-wasi = "3.1"
hashbrown = "0.14"
merkle-cbt = "0.3"
backoff = "0.4.0"
