[workspace]
members = [
    "agoranet",
    "runtime",
    "wallet",
    "runtime/crates/*",
    "wallet/crates/*"
]

[workspace.dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
libp2p = "0.53"
multihash = { version = "0.16.3", features = ["sha2"] }
cid = { version = "0.10.1", features = ["serde"] }
clap = { version = "4.4", features = ["derive"] }
futures = "0.3"
