[workspace]
members = [
  "backend",
  "frontend",
  "contracts",
  "crates/core",
  "crates/consensus",
  "crates/networking",
  "crates/storage",
  "crates/runtime",
  "crates/resources",
  "crates/finance"
]

[workspace.dependencies]
tokio = { version = "1.30", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
warp = "0.3"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio"] }
