[workspace]
resolver = "2"
members = [
    "agoranet",
    "runtime",
    "runtime/cli",
    "wallet",
    "runtime/crates/*",
    "wallet/crates/*"
]
exclude = [
    # No need to exclude agoranet since it's already included as a member
    "wallet/crates/ffi"  # Exclude FFI crate if it needs special handling
]

[workspace.dependencies]
# Common dependencies
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
futures = "0.3"
clap = { version = "4.4", features = ["derive"] }

# Network and storage
libp2p = "0.53"
multihash = { version = "0.18.1", features = ["sha2"] } # Updated to 0.18.1 per fix-wallet-sync.md
cid = { version = "0.10.1", features = ["serde"] }

# IPLD related dependencies
# Note: libipld is officially deprecated in favor of ipld-core, but we'll keep both for compatibility
libipld = { version = "0.16", features = ["derive"] }
libipld-core = "0.13.1"
# For DAG-CBOR serialization - using the recommended libraries
serde_ipld_dagcbor = "0.4"
ipld-core = "0.3"

# Identity and security
# Using ssi 0.7 with features that are available
ssi = { version = "0.7", features = ["ed25519", "rsa"] }
did-method-key = "0.2"
ed25519-dalek = "1.0"
sha2 = "0.10"
base64 = { version = "0.21", features = ["std"] }
rand = "0.8"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.3", features = ["v4", "serde"] }
reqwest = { version = "0.11", features = ["json"] }
hex = "0.4"

# Runtime-specific dependencies
wasmer = "3.1"
wasmer-wasi = "3.1"
hashbrown = "0.14"
merkle-cbt = "0.3"
backoff = "0.4.0"
