[workspace]
members = [
  "backend",
  "frontend",
  "contracts",
  "crates/icn-types",
  "crates/icn-core",
  "crates/icn-consensus",
  "crates/icn-networking",
  "crates/icn-storage",
  "crates/icn-runtime",
  "crates/icn-resource",
  "crates/icn-finance",
  "crates/icn-federation",
  "crates/icn-governance",
  "crates/icn-reputation",
  "crates/icn-crypto",
  "crates/icn-p2p",
  "crates/icn-dsl",
  "crates/icn-mutual-credit"
]

[workspace.dependencies]
icn-types = { path = "crates/icn-types" }
tokio = { version = "1.30", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
warp = "0.3"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio"] }
thiserror = "1.0"
chrono = { version = "0.4", features = ["serde"] }

[package]
name = "icn"
version = "0.1.0"
description = "Inter-Cooperative Network - A platform for cooperative resource sharing and governance"
edition = "2021"

[features]
default = ["basic"]
basic = []
federation = ["dep:tokio", "dep:async-trait"]
advanced-governance = ["dep:parity-scale-codec"]
monitoring = ["dep:prometheus"]

[dependencies]
icn-types = { workspace = true }
tokio = { workspace = true, optional = true }
async-trait = { version = "0.1", optional = true }
parity-scale-codec = { version = "3.0", optional = true }
prometheus = { version = "0.13", optional = true }
serde = { workspace = true }

[lib]
name = "icn_lib"
path = "src/lib.rs"

[[bin]]
name = "icn_bin"
path = "src/main.rs"
