[workspace]
members = [
  "backend",
  "frontend",
  "contracts",
  "crates/core",
  "crates/consensus",
  "crates/networking",
  "crates/storage",
  "crates/runtime",
  "crates/resources",
  "crates/finance"
]

[workspace.dependencies]
tokio = { version = "1.30", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
warp = "0.3"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio"] }

[package]
name = "icn"
version = "0.1.0"

[features]
default = ["basic"]
basic = []
federation = ["dep:tokio", "dep:async-trait"]
advanced-governance = ["dep:parity-scale-codec"]
monitoring = ["dep:prometheus"]

[dependencies]
tokio = { version = "1.0", optional = true }
async-trait = { version = "0.1", optional = true }
parity-scale-codec = { version = "3.0", optional = true }
prometheus = { version = "0.13", optional = true }
