version: '3.8'

services:
  test-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: icndb_test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      TEST_DATABASE_URL: postgres://postgres:postgres@test-db:5432/icndb_test
      RUST_LOG: debug
      RUST_BACKTRACE: 1
    volumes:
      - .:/app
      - test-results:/app/test-results
      - cargo-cache:/usr/local/cargo/registry
    depends_on:
      test-db:
        condition: service_healthy
    command: ["./scripts/run_tests.sh"]

  k6:
    image: grafana/k6:latest
    volumes:
      - ./tests/load_tests:/scripts
      - ./test-results/k6:/results
    environment:
      K6_OUT: json=/results/k6-results.json
    depends_on:
      - test-runner

volumes:
  test-results:
  cargo-cache: 