[package]
name = "icn-net"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
quinn.workspace = true
rustls.workspace = true
tokio-rustls.workspace = true
mdns-sd.workspace = true
icn-identity.workspace = true
icn-gossip.workspace = true
icn-trust.workspace = true
icn-ledger.workspace = true
icn-store.workspace = true
icn-obs.workspace = true
icn-snapshot.workspace = true
icn-security.workspace = true
sha2.workspace = true
serde.workspace = true
serde_json = "1.0"
bincode.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
bytes.workspace = true
futures.workspace = true
rcgen = "0.13"
time = "0.3"
ed25519-dalek.workspace = true
x25519-dalek.workspace = true
chacha20poly1305.workspace = true
zeroize.workspace = true
hostname = "0.4"
x509-parser = "0.16"
rand = "0.8"
bitflags = "2.4"

[dev-dependencies]
icn-store.workspace = true
tracing-subscriber.workspace = true
rand_core.workspace = true
