[package]
name = "backend"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1.30", features = ["full"] }
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio"] }
icn-federation = { path = "../crates/icn-federation" }
tower = { version = "0.4", features = ["limit"] }
tower-http = { version = "0.4", features = ["limit"] }
bls-signatures = "0.8"
didcomm-rs = "0.1"

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio"] }
quickcheck = "1.0"
quickcheck_async = "0.1"
quickcheck_macros = "1.0"
tokio-test = "0.4"
test-log = "0.2"
env_logger = "0.10"
pretty_assertions = "1.4"
fake = { version = "2.8", features = ["derive"] }
rstest = "0.18"
mockall = "0.11"
async-trait = "0.1"
futures = "0.3"

[[bench]]
name = "governance_benchmarks"
harness = false
