[package]
name = "backend"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1.30", features = ["full"] }
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio"] }
icn-federation = { path = "../crates/icn-federation" }
tower = { version = "0.4", features = ["limit"] }
tower-http = { version = "0.4", features = ["limit"] }
bls-signatures = "0.8"
didcomm-rs = "0.1"
