[package]
name = "icn-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
icn-types = { path = "../crates/icn-types" }
icn-core = { path = "../crates/icn-core" }
icn-consensus = { path = "../crates/icn-consensus" }
icn-crypto = { path = "../crates/icn-crypto" }
icn-p2p = { path = "../crates/icn-p2p" }
icn-runtime = { path = "../crates/icn-runtime" }
icn-storage = { path = "../crates/icn-storage" }
