[package]
name = "icn-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
warp = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
sqlx = { workspace = true, features = ["sqlite", "runtime-tokio-native-tls"] }
thiserror = { workspace = true }
dashmap = "5.5"
futures = { workspace = true }
async-trait = { workspace = true }
actix-web = "4.0"
serde_yaml = "0.8"
uuid = { version = "1", features = ["serde", "v4"] }
reqwest = { version = "0.11", features = ["json"] }
tokio-tungstenite = "0.15"
tracing = { workspace = true }
tracing-subscriber = "0.3"
prometheus = "0.13"
opentelemetry = { version = "0.16", features = ["rt-tokio"] }
opentelemetry-jaeger = "0.16"
opentelemetry-prometheus = "0.16"
opentelemetry-zipkin = "0.16"
opentelemetry-otlp = "0.16"
