[package]
name = "icn-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4"] }
log = "0.4"
env_logger = "0.9"
futures-util = "0.3"
sqlx = { version = "0.6", features = ["postgres", "runtime-tokio-rustls"] }
thiserror = "1.0"
dashmap = "5.4"
lazy_static = "1.4"
reqwest = { version = "0.11", features = ["json"] }
icn-types = { path = "../crates/icn-types" }
async-trait = "0.1"
sha2 = "0.10"
toml = "0.7"
tokio-tungstenite = "0.21"
