[package]
name = "icn-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.11"
sqlx = { version = "0.8.3", features = ["sqlite", "runtime-tokio-native-tls"] }
thiserror = "1.0"
dashmap = "5.5"
futures = "0.3"
async-trait = "0.1"
actix-web = "4.0"
serde_yaml = "0.8"
uuid = { version = "1", features = ["serde", "v4"] }
reqwest = { version = "0.11", features = ["json"] }
tokio-tungstenite = "0.15"
tracing = "0.1"
tracing-subscriber = "0.3"
prometheus = "0.13"
opentelemetry = { version = "0.16", features = ["rt-tokio"] }
opentelemetry-jaeger = "0.16"
opentelemetry-prometheus = "0.16"
opentelemetry-zipkin = "0.16"
opentelemetry-otlp = "0.16"
