[package]
name = "icn-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
# Async runtime
tokio = { version = "1.0", features = ["full"] }

# HTTP and WebSocket handling
warp = "0.3"
tokio-tungstenite = { version = "0.20", features = ["native-tls"] }
url = "2.4"
http = "0.2"

# Serialization and data handling
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4"] }

# Futures and concurrency
futures = "0.3"
futures-util = "0.3"

# Random number generation
rand = "0.8"

# Cryptography
secp256k1 = { version = "0.24.3", features = ["rand"] }
sha2 = "0.10"

[dev-dependencies]
# Used for development tests
tokio = { version = "1.0", features = ["full"] }
warp = "0.3"

[features]
default = []

# Optional Features (if needed for CI or other setups)
test = []
