[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { workspace = true }
tokio = { workspace = true }
warp = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
thiserror = { workspace = true }
icn-types = { workspace = true }
icn-federation = { path = "../crates/icn-federation" }
tower = { version = "0.4", features = ["limit"] }
tower-http = { version = "0.6", features = ["limit"] }
bls-signatures = "=0.7.1"  # Pinned to older version compatible with Rust 1.71.1
didcomm-rs = "0.1"
tokio-tungstenite = "=0.18.0"
tungstenite = "=0.18.0"
url = "=2.3.1"

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio"] }
quickcheck = "1.0"
quickcheck_async = "0.1"
quickcheck_macros = "1.0"
tokio-test = "0.4"
test-log = "0.2"
pretty_assertions = "1.4"
fake = { version = "2.8", features = ["derive"] }
rstest = "0.25"
mockall = "0.11"
futures = "0.3"

[[bench]]
name = "governance_benchmarks"
harness = false
