[package]
name = "icn-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
icn-types = { path = "../crates/icn-types" }
icn-core = { path = "../crates/icn-core" }
icn-consensus = { path = "../crates/icn-consensus" }
icn-crypto = { path = "../crates/icn-crypto" }
icn-p2p = { path = "../crates/icn-p2p" }
icn-runtime = { path = "../crates/icn-runtime" }
icn-storage = { path = "../crates/icn-storage" }
serde = "1.0"
secp256k1 = "0.21"
chrono = "0.4"
sha2 = "0.9"
tokio-tungstenite = "0.15"
warp = "0.3"
futures-util = "0.3"
hashbrown = "0.11"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
