[package]
name = "icn-backend"
version = "0.1.0"
edition = "2021"

[dependencies]

secp256k1 = { version = "0.24.3", features = ["rand"] }
sha2 = "0.10.8"
async-trait = "0.1.77"
tokio-postgres = "0.7.10"
serial_test = "2.0.0"

[dev-dependencies]
