apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: icn-backups
  namespace: icn
  labels:
    app: icn
    component: backup
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 20Gi
