apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: icn

resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - services.yaml
  - monitoring/servicemonitor.yaml

# Images can be overridden with kustomize
images:
  - name: icn
    newName: icn
    newTag: latest

