apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: icn

resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - backup-pvc.yaml
  - deployment.yaml
  - services.yaml
  - pdb.yaml
  - network-policies.yaml
  - pilot-ui-deployment.yaml
  - backup-cronjob.yaml
  - prometheusrule.yaml
  - grafana-dashboard.yaml
  - monitoring/servicemonitor.yaml

# Images can be overridden with kustomize
images:
  - name: icn
    newName: icn
    newTag: latest

