[package]
name = "icn-wallet-root"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]
resolver = "2"
members = [
  "crates/wallet-core",
  "crates/wallet-agent",
  "crates/wallet-sync",
  "crates/wallet-ui-api",
  # "crates/wallet-ffi", # Temporarily disabled until we fix other crates
  "crates/wallet-types",
  "cli"
]

# Dependencies are now inherited from the root workspace
[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
