[package]
name = "storage"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }

[lib]
name = "storage"
path = "src/lib.rs"
