[package]
name = "icn-storage"
version = "0.1.0"
edition = "2021"
description = "Storage backends for the ICN Runtime"

[dependencies]
# Core dependencies from workspace
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true, features = ["sync", "rt-multi-thread", "macros", "fs"] }
async-trait = { workspace = true }

# IPLD and content-addressing
cid = { workspace = true }
multihash = { workspace = true }
libipld = { workspace = true }

# ICN dependencies
icn-common = { path = "../common" }
# Break circular dependency - make dag optional and only used for tests or specific features
icn-dag = { path = "../dag", optional = true }
icn-identity = { path = "../identity" }

# Additional dependencies
serde_bytes = "0.11"
once_cell = "1.19"
itertools = "0.12.1"
uuid = { workspace = true }
chrono = { workspace = true }
sha2 = { workspace = true }
hashbrown = { workspace = true }

# Storage backends
rocksdb = { version = "0.21", default-features = false, features = ["multi-threaded-cf"], optional = true }

[dev-dependencies] 
tempfile = "3.9.0"
# For tests we need the dag crate
icn-dag = { path = "../dag" }

[features]
default = ["memory-storage"]
rocksdb-storage = ["rocksdb"]
memory-storage = []
with-dag = ["icn-dag"]
