[package]
name = "icn-storage"
version = "0.1.0"
edition = "2021"
description = "Storage backends for the ICN Runtime"

[dependencies]
# Use workspace dependencies where available
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
cid = { workspace = true }
multihash = { workspace = true }
tokio = { workspace = true, features = ["sync", "rt-multi-thread", "macros", "fs"] }
async-trait = { workspace = true }
futures = { workspace = true }

# Add dependency to common crate
icn-common = { path = "../common" }

# Add dependency to libipld
libipld = { workspace = true }

# Add identity crate
icn-identity = { path = "../identity" }

# Other dependencies
# rocksdb = "0.21"
serde_bytes = "0.11"
once_cell = "1.19"
itertools = "0.12.1"
tempfile = "3.9.0"
uuid = { version = "1.4.1", features = ["v4", "serde"] }
chrono = { version = "0.4.33", features = ["serde"] }
sha2 = "0.10.9"
# Make RocksDB optional through a feature flag
rocksdb = { version = "0.21", default-features = false, features = ["multi-threaded-cf"], optional = true }

[dev-dependencies] 
tempfile = "3.9.0"

[features]
default = ["memory-storage"]
rocksdb-storage = ["rocksdb"]
memory-storage = []
