[package]
name = "icn-runtime-root"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]
members = [
    "crates/core-vm",
    "crates/governance-kernel",
    "crates/dag",
    "crates/identity",
    "crates/economics",
    "crates/federation",
    "crates/storage",
    "crates/agoranet-integration",
    "crates/execution-tools",
    "crates/ccl-compiler",
    "cli",
]
resolver = "2"

# Dependencies are now inherited from the root workspace
[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# Additional crate-specific dependencies not in root workspace
[workspace.dependencies]
wasmer = "3.1"
wasmer-wasi = "3.1"
did-method-key = "0.2"
hashbrown = "0.14"
merkle-cbt = "0.3"
libipld-core = "0.13.1" 
