[workspace]
members = [
    "crates/core-vm",
    "crates/governance-kernel",
    "crates/dag",
    "crates/identity",
    "crates/economics",
    "crates/federation",
    "crates/storage",
    "crates/agoranet-integration",
    "crates/execution-tools",
    "crates/ccl-compiler",
    "cli",
]
resolver = "2"

[workspace.dependencies]
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
wasmer = "3.1"
wasmer-wasi = "3.1"
libp2p = "0.53"
multihash = { version = "0.16.3", features = ["sha2"] }
cid = { version = "0.10.1", features = ["serde"] }
did-method-key = "0.2"
hashbrown = "0.14"
merkle-cbt = "0.3"
async-trait = "0.1"
libipld-core = "0.13.1"
futures = "0.3" 
