[package]
name = "icn-wallet-agent"
version = "0.1.0"
edition = "2021"
description = "ICN Wallet Agent for working with distributed execution receipts"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
# icn-wallet-sync = { path = "../sync" } # Temporarily disabled due to exclusion
icn-wallet-core = { path = "../wallet-core" }
icn-dag = { path = "../../../runtime/crates/dag" }
chrono = { workspace = true }
x25519-dalek = "2.0"
rand = { workspace = true }
base64 = { workspace = true }
aes-gcm = "0.10"
url = "2.3" 