[package]
name = "wallet-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
wallet-core = { path = "../wallet-core" }
wallet-types = { path = "../wallet-types" }
wallet-ffi = { path = "../wallet-ffi", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.34", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.4", features = ["v4", "serde"] }
async-trait = "0.1"
base64 = "0.21.0"
thiserror = "1.0"
tracing = "0.1"
futures = "0.3"
reqwest = { version = "0.11", features = ["json"] }
backoff = { version = "0.4", features = ["futures", "tokio"] }

[features]
default = []
ffi = ["wallet-ffi"]

[dev-dependencies]
tokio-test = "0.4"
mockito = "1.2"
