[package]
name = "icn-wallet-ffi-old"
version = "0.1.0"
edition = "2021"
description = "FFI bindings for ICN wallet (old location)"

[lib]
name = "icn_wallet_ffi_old"
path = "src/lib.rs"

[dependencies]
# Add dependencies as needed 