[package]
name = "icn-wallet-ffi"
version = "0.1.0"
edition = "2021"
description = "FFI bindings for ICN wallet"

[lib]
name = "icn_wallet_ffi"
crate-type = ["staticlib", "cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
# Add dependencies as needed 