[package]
name = "wallet-sync"
version = "0.1.0"
edition = "2021"
description = "Wallet synchronization module for ICN"

[dependencies]
# Use workspace dependencies
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
ed25519-dalek = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
reqwest = { workspace = true }
uuid = { workspace = true }

# Specialized dependencies with version pinning
# Use a renamed multihash to avoid version conflicts
multihash-0_16_3 = { package = "multihash", version = "=0.16.3", features = ["sha2"] }
# Pin backoff to exactly match the workspace version
backoff = { version = "0.4.0", features = ["futures", "tokio"] }
# Add hex dependency for CID generation
hex = "0.4"

# Internal dependencies
wallet-identity = { path = "../identity" }
wallet-storage = { path = "../storage" } 