[package]
name = "icn-agoranet-integration"
version = "0.1.0"
edition = "2021"
description = "Deliberation thread linking logic stub for the ICN Runtime"

[dependencies]
icn-identity = { path = "../icn-identity" }
icn-dag = { path = "../icn-dag" }
icn-governance-kernel = { path = "../icn-governance-kernel" }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
cid = { workspace = true }
uuid = { version = "1.3", features = ["v4", "serde"] }
async-trait = { workspace = true }
reqwest = { version = "0.11", features = ["json"] }

[dev-dependencies]
tokio = { version = "1.29", features = ["rt", "macros"] }
mockito = "1.2" 