# Community Federation Configuration
# This represents an open community federation model with permissioned validators

name = "Beta Community Federation"
did = "did:icn:federation:beta-community"
genesis_node = "did:icn:federation:beta-genesis"
federation_type = "Community"
description = "An open community federation with permissioned validators and public observers"

# Initial nodes configuration
[[nodes]]
did = "did:icn:federation:beta-genesis"
role = "Validator"
endpoint = "https://beta-genesis.example.org"

[[nodes]]
did = "did:icn:federation:beta-node1"
role = "Validator"
endpoint = "https://beta-node1.example.org"

[[nodes]]
did = "did:icn:federation:beta-node2"
role = "Validator"
endpoint = "https://beta-node2.example.org"

[[nodes]]
did = "did:icn:federation:beta-observer1"
role = "Observer"
endpoint = "https://beta-observer1.example.org"

[[nodes]]
did = "did:icn:federation:beta-observer2"
role = "Observer"
endpoint = "https://beta-observer2.example.org"

[[nodes]]
did = "did:icn:federation:beta-archiver1"
role = "Archiver"
endpoint = "https://beta-archiver1.example.org"

# Federation parameters
[parameters]
quorum_threshold = 2
token_supply = 5000000
governance_voting_period = 259200  # 3 days in seconds
credential_timeout = 14400  # 4 hours in seconds
dag_anchor_interval = 300  # 5 minutes in seconds
trust_bundle_epoch_interval = 432000  # 5 days in seconds
observer_permission = "public"  # Anyone can run observer nodes

# Governance rules
[governance]
proposal_token_requirement = 100
community_proposal_allowed = true
veto_threshold = 51  # 51% of validators can veto
amendment_threshold = 66  # 66% required for amendments
validator_admission_threshold = 75  # 75% required to admit new validators

# Economics
[economics]
initial_distribution = [
  { did = "did:icn:federation:beta-genesis", amount = 1000000 },
  { did = "did:icn:federation:beta-node1", amount = 1000000 },
  { did = "did:icn:federation:beta-node2", amount = 1000000 },
  { did = "did:icn:federation:beta-observer1", amount = 100000 },
  { did = "did:icn:federation:beta-observer2", amount = 100000 },
  { did = "did:icn:federation:beta-archiver1", amount = 800000 },
  { did = "did:icn:federation:community-fund", amount = 1000000 }
]

# Community governance
[community]
open_participation = true
community_token_allocation = 1000000
community_proposal_threshold = 50  # 50 community tokens to make a proposal
reputation_enabled = true 