# Cooperative Federation Configuration
# This represents a production-oriented cooperative federation model

name = "Alpha Cooperative Federation"
did = "did:icn:federation:alpha-cooperative"
genesis_node = "did:icn:federation:alpha-genesis"
federation_type = "Cooperative"
description = "A cooperative federation with equal governance rights across members"

# Initial nodes configuration
[[nodes]]
did = "did:icn:federation:alpha-genesis"
role = "Validator"
endpoint = "https://alpha-genesis.example.com"

[[nodes]]
did = "did:icn:federation:alpha-node1"
role = "Validator"
endpoint = "https://alpha-node1.example.com"

[[nodes]]
did = "did:icn:federation:alpha-node2"
role = "Validator"
endpoint = "https://alpha-node2.example.com"

[[nodes]]
did = "did:icn:federation:alpha-node3"
role = "Validator"
endpoint = "https://alpha-node3.example.com"

[[nodes]]
did = "did:icn:federation:alpha-archiver1"
role = "Archiver"
endpoint = "https://alpha-archiver1.example.com"

# Federation parameters
[parameters]
quorum_threshold = 3
token_supply = 10000000
governance_voting_period = 172800  # 48 hours in seconds
credential_timeout = 7200  # 2 hours in seconds
dag_anchor_interval = 600  # 10 minutes in seconds
trust_bundle_epoch_interval = 604800  # 7 days in seconds

# Governance rules
[governance]
proposal_token_requirement = 1000
veto_threshold = 66  # 66% of validators can veto
amendment_threshold = 75  # 75% required for amendments

# Economics
[economics]
initial_distribution = [
  { did = "did:icn:federation:alpha-genesis", amount = 2000000 },
  { did = "did:icn:federation:alpha-node1", amount = 2000000 },
  { did = "did:icn:federation:alpha-node2", amount = 2000000 },
  { did = "did:icn:federation:alpha-node3", amount = 2000000 },
  { did = "did:icn:federation:alpha-archiver1", amount = 1000000 },
  { did = "did:icn:federation:reserve", amount = 1000000 }
] 