# ICN Federation Configuration File

# Basic federation information
name = "ICN Test Federation"
did = "did:icn:federation:test-federation"
genesis_node = "did:icn:federation:genesis"
federation_type = "Development"
description = "Development test federation for ICN Runtime"

# Initial nodes configuration
[[nodes]]
did = "did:icn:federation:genesis"
role = "Validator"
endpoint = "http://federation-node-genesis:9000"

[[nodes]]
did = "did:icn:federation:node1"
role = "Validator"
endpoint = "http://federation-node-1:9000"

[[nodes]]
did = "did:icn:federation:node2"
role = "Validator"
endpoint = "http://federation-node-2:9000"

# Federation parameters
[parameters]
quorum_threshold = 2
token_supply = 1000000
governance_voting_period = 86400  # 24 hours in seconds
credential_timeout = 3600  # 1 hour in seconds
dag_anchor_interval = 300  # 5 minutes in seconds
trust_bundle_epoch_interval = 86400  # 24 hours in seconds 