[package]
name = "icn-covm"
version = "0.1.0"
edition = "2021"
description = "Command-line interface for the ICN Runtime (CoVM V3)"

[lib]
path = "lib.rs"

[dependencies]
clap = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { version = "1.28", features = ["full"] }
cid = { workspace = true }
futures = { workspace = true }
uuid = { version = "1.4", features = ["v4", "serde"] }

# ICN crates
icn-core-vm = { path = "../crates/core-vm" }
icn-governance-kernel = { path = "../crates/governance-kernel" }
icn-identity = { path = "../crates/identity" }
icn-storage = { path = "../crates/storage" }
icn-economics = { path = "../crates/economics" }

[[bin]]
name = "covm"
path = "covm.rs" 