[package]
name = "icn-covm"
version = "0.1.0"
edition = "2021"
description = "Command-line interface for the ICN Runtime (CoVM V3)"

[dependencies]
clap = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[[bin]]
name = "covm"
path = "covm.rs" 