[package]
name = "icn-crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
lazy_static = "1.4"
rayon = "1.6"
chrono = { version = "0.4", features = ["serde"] }
bincode = "1.3"
