version: "3.8"

services:
  # PostgreSQL database service
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-icnuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-icnpass}
      POSTGRES_DB: ${POSTGRES_DB:-icndb}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U icnuser -d icndb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    networks:
      - icn-network

  # Backend service - Rust application
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"
    volumes:
      - backend_data:/data
      - backend_logs:/logs
      - backend_config:/config
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER:-icnuser}:${POSTGRES_PASSWORD:-icnpass}@db:5432/${POSTGRES_DB:-icndb}?options=-c%20search_path%3Dicn
      - RUST_LOG=${RUST_LOG:-info}
      - RUST_BACKTRACE=${RUST_BACKTRACE:-0}
    healthcheck:
      test: ["CMD", "curl", "-X", "GET", "http://localhost:8081/api/v1/health", "||", "exit", "1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - icn-network

  # Frontend service - React application
  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
      args:
        - REACT_APP_API_URL=/api
    restart: unless-stopped
    depends_on:
      - backend  # Changed from condition: service_healthy to just the service name
    ports:
      - "80:80"
    environment:
      - API_URL=http://backend:8081/api
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - icn-network

  # ICN Bootstrap Node
  bootstrap:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    container_name: icn-bootstrap
    environment:
      - NODE_TYPE=bootstrap
      - NODE_PORT=9000
      - API_PORT=8082
      - BOOTSTRAP_NODES=[]
      - COOPERATIVE_ID=${COOPERATIVE_ID:-icn-primary}
      - COOPERATIVE_TIER=provider
      - LOG_LEVEL=${RUST_LOG:-info}
      - DATABASE_URL=postgres://${POSTGRES_USER:-icnuser}:${POSTGRES_PASSWORD:-icnpass}@db:5432/${POSTGRES_DB:-icndb}
    ports:
      - "9000:9000"
      - "8082:8082"
    volumes:
      - bootstrap_data:/data
      - bootstrap_logs:/logs
    depends_on:
      - db
    networks:
      - icn-network
    restart: unless-stopped

  # ICN Validator Node 1
  validator1:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    container_name: icn-validator1
    environment:
      - NODE_TYPE=validator
      - NODE_PORT=9001
      - API_PORT=8083
      - BOOTSTRAP_NODES=["ws://bootstrap:9000"]
      - COOPERATIVE_ID=${COOPERATIVE_ID:-icn-primary}
      - COOPERATIVE_TIER=validator
      - LOG_LEVEL=${RUST_LOG:-info}
      - DATABASE_URL=postgres://${POSTGRES_USER:-icnuser}:${POSTGRES_PASSWORD:-icnpass}@db:5432/${POSTGRES_DB:-icndb}
    ports:
      - "9001:9001"
      - "8083:8083"
    volumes:
      - validator1_data:/data
      - validator1_logs:/logs
    depends_on:
      - bootstrap
      - db
    networks:
      - icn-network
    restart: unless-stopped

  # ICN Validator Node 2
  validator2:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    container_name: icn-validator2
    environment:
      - NODE_TYPE=validator
      - NODE_PORT=9002
      - API_PORT=8084
      - BOOTSTRAP_NODES=["ws://bootstrap:9000"]
      - COOPERATIVE_ID=${COOPERATIVE_ID:-icn-primary}
      - COOPERATIVE_TIER=validator
      - LOG_LEVEL=${RUST_LOG:-info}
      - DATABASE_URL=postgres://${POSTGRES_USER:-icnuser}:${POSTGRES_PASSWORD:-icnpass}@db:5432/${POSTGRES_DB:-icndb}
    ports:
      - "9002:9002"
      - "8084:8084"
    volumes:
      - validator2_data:/data
      - validator2_logs:/logs
    depends_on:
      - bootstrap
      - db
    networks:
      - icn-network
    restart: unless-stopped

volumes:
  db_data:
    name: icn_db_data
  backend_data:
    name: icn_backend_data
  backend_logs:
    name: icn_backend_logs
  backend_config:
    name: icn_backend_config
  bootstrap_data:
    name: icn_bootstrap_data
  bootstrap_logs:
    name: icn_bootstrap_logs
  validator1_data:
    name: icn_validator1_data
  validator1_logs:
    name: icn_validator1_logs
  validator2_data:
    name: icn_validator2_data
  validator2_logs:
    name: icn_validator2_logs

networks:
  icn-network:
    driver: bridge
