version: "3.8"

services:
  # PostgreSQL database service
  db:
    image: postgres:13-alpine
    # Changed from postgres:14-alpine to postgres:13-alpine to match existing data
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-icnuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-icnpass}
      POSTGRES_DB: ${POSTGRES_DB:-icndb}
    ports:
      - "5432:5432"
    networks:
      - icn-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-icnuser} -d ${POSTGRES_DB:-icndb}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend service - Development mode with hot reloading
  backend:
    build:
      context: ..
      dockerfile: backend.Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"
    volumes:
      - ../backend:/usr/src/app/backend
      - ../crates:/usr/src/app/crates
      - cargo_cache:/usr/local/cargo/registry
      - target_cache:/usr/src/app/target
      - backend_logs:/logs
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER:-icnuser}:${POSTGRES_PASSWORD:-icnpass}@db:5432/${POSTGRES_DB:-icndb}
      - RUST_LOG=${RUST_LOG:-debug}
      - RUST_BACKTRACE=1
    networks:
      - icn-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend service - Development mode with hot reloading
  frontend:
    build:
      context: ..
      dockerfile: frontend.Dockerfile
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3000:3000"
      - "35729:35729"  # For live reload
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8081/api
      - NODE_ENV=development
    networks:
      - icn-network

volumes:
  db_data:
  cargo_cache:
  target_cache:
  backend_logs:

networks:
  icn-network:
    driver: bridge