version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: ["cargo", "run", "--release"]

  test:
    build:
      context: .
      dockerfile: backend.Dockerfile
    command: ["cargo", "test", "--release"]

  docs:
    image: squidfunk/mkdocs-material:latest
    volumes:
      - ../docs:/docs                    # Maps the correct docs directory
    ports:
      - "8000:8000"
    working_dir: /docs                   # Set the working directory to /docs inside the container
    command: serve -a 0.0.0.0:8000       # Run MkDocs without prefixing `mkdocs`
