version: "3.3"

services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://icnuser:icnpass@db:5432/icndb
      - RUST_LOG=info
    depends_on:
      - db
    networks:
      - icn-network

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - icn-network

  db:
    image: postgres:13.3
    restart: unless-stopped
    environment:
      POSTGRES_USER: icnuser
      POSTGRES_PASSWORD: icnpass
      POSTGRES_DB: icndb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - icn-network

volumes:
  db_data:

networks:
  icn-network:
    driver: bridge
