version: "3.8"

services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://icnuser:icnpass@db:5432/icndb
    depends_on:
      db:
        condition: service_healthy  # Ensures DB is ready before backend starts
    networks:
      - icn-network

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - icn-network

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: icnuser
      POSTGRES_PASSWORD: icnpass
      POSTGRES_DB: icndb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U icnuser -d icndb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - icn-network
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist DB data

  docs:
    image: squidfunk/mkdocs-material:latest
    volumes:
      - ../docs:/docs
    ports:
      - "8000:8000"
    working_dir: /docs
    command: /bin/sh -c "pip install mkdocs-mermaid2-plugin && mkdocs serve -a 0.0.0.0:8000"
    networks:
      - icn-network

volumes:
  db_data:  # Persistent storage for database

networks:
  icn-network:
    driver: bridge
