//! Cooperative configuration for cooperative-specific settings

use serde::{Deserialize, Serialize};

/// Cooperative configuration for cooperative-specific settings
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CooperativeConfig {
    /// Treasury DID for the cooperative
    /// This DID is used as the source for budget payouts and other financial operations.
    /// If not set, the node's own DID will be used as a fallback.
    /// Format: "did:icn:<base58-pubkey>"
    #[serde(default)]
    pub treasury_did: Option<String>,

    /// Cooperative display name (human-readable)
    #[serde(default)]
    pub name: Option<String>,

    /// Cooperative description
    #[serde(default)]
    pub description: Option<String>,
}

impl CooperativeConfig {
    /// Resolve the treasury principal whose DID authors governance-authored
    /// ledger entries, or explain why it cannot be resolved.
    ///
    /// Three cases, and only two of them are the same thing:
    ///
    /// * **unset** — a node that never underwent institutional genesis. The
    ///   node's own DID is used, which is what every pre-genesis deployment has
    ///   always done. Deliberately preserved.
    /// * **set and usable** — an institution whose treasury principal was
    ///   generated by `icnctl institution runtime-root create` (#2744).
    /// * **set and unusable** — refused.
    ///
    /// That third case used to be folded into the first by an `.ok()`, so a
    /// configured-but-unparseable treasury silently became the node DID: the
    /// operator asked for an institutional treasury and got the machine, logged
    /// as "No treasury_did configured", which was false.
    ///
    /// # Scope of the refusal
    ///
    /// A configured-but-unusable value now refuses at startup where it
    /// previously started on the node DID. That is deliberate and is scoped by
    /// construction rather than by a genesis marker: nothing in this repository
    /// ever generated a `[cooperative]` section before `icnctl institution
    /// genesis` existed, so the only way to reach this arm on an existing
    /// deployment is a hand-edited configuration that names a treasury the
    /// daemon cannot parse. Starting such a node on its own DID is the silent
    /// substitution #2744 exists to remove, so refusing is the intended
    /// behaviour rather than a migration hazard. Deployments with no
    /// `[cooperative]` section — every pre-genesis node — are untouched.
    ///
    /// It is not a hypothetical. `Did` parsing requires the bytes after
    /// `did:icn:` to decode to exactly 32 bytes *and* form a valid Ed25519
    /// point, and both treasury spellings this repository already produces fail
    /// that: the cooperative crate's `derive_treasury_did` emits `did:icn:treasury:<bs58>`, which is not
    /// multibase at all, and `Did::from_anchor_id` emits 16 hashed bytes
    /// zero-padded to 32, which lands on the curve only about half the time.
    /// A keypair-backed genesis treasury DID always parses.
    pub fn resolve_treasury_did(
        &self,
        node_did: &icn_identity::Did,
    ) -> anyhow::Result<TreasuryDid> {
        match self.parse_configured_treasury_did()? {
            None => Ok(TreasuryDid::NodeFallback(node_did.clone())),
            Some(configured) => Ok(TreasuryDid::Configured(configured)),
        }
    }

    /// The one rule for "is the configured treasury DID usable?".
    ///
    /// Both [`Self::resolve_treasury_did`] — the startup path — and
    /// `Config::validate` — the `--validate-config` path — go through here, so
    /// they cannot drift into two independently maintained definitions of the
    /// same acceptance. `--validate-config` is documented as predicting whether
    /// the daemon accepts a file; two parsers would make that prediction true
    /// only until someone changed one of them.
    ///
    /// Structural only. This parses the string. It opens no store, needs no key
    /// material, and does not ask whether that treasury exists or is
    /// authorized — those are runtime questions, and validation is not a
    /// deployment-readiness check.
    ///
    /// `None` means no treasury was configured, which is the legacy node-DID
    /// fallback and not an error.
    pub fn parse_configured_treasury_did(&self) -> anyhow::Result<Option<icn_identity::Did>> {
        match self.treasury_did.as_ref() {
            None => Ok(None),
            Some(configured) => configured
                .parse::<icn_identity::Did>()
                .map(Some)
                .map_err(|e| {
                    anyhow::anyhow!(
                        "Configured [cooperative] treasury_did {configured:?} is not a usable \
                         DID ({e}). Refusing to start rather than silently substituting this \
                         node's own DID as the cooperative's treasury (#2744)."
                    )
                }),
        }
    }
}

/// Which of the two legitimate outcomes [`CooperativeConfig::resolve_treasury_did`]
/// produced.
///
/// The distinction is kept in the type rather than left as a bare `Did` so a
/// caller cannot accidentally treat "this institution's treasury" and "no
/// treasury was configured, so the machine stands in" as the same fact.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TreasuryDid {
    /// A treasury principal named by the configuration.
    ///
    /// **`Configured`, not `Institutional`.** Parsing a DID out of
    /// `[cooperative] treasury_did` establishes that a treasury was configured
    /// and that the value is usable. It establishes nothing about *provenance*:
    /// there is no receipt, no cooperative registration and no governance
    /// behind it, and a hand-written file naming this node's own DID would land
    /// here too. `docs/architecture/IDENTITY_SEMANTICS.md` reserves
    /// institutional meaning for governed `EntityId` semantics, so calling this
    /// variant institutional would re-import at the type level exactly the
    /// claim icn#2744 spent its scope disclaiming. Callers that need the
    /// stronger fact establish it themselves — `institution runtime-root`
    /// checks this DID against its receipt.
    Configured(icn_identity::Did),
    /// No treasury configured; the node's DID, as every pre-genesis
    /// deployment has always used.
    NodeFallback(icn_identity::Did),
}

impl TreasuryDid {
    pub fn did(&self) -> &icn_identity::Did {
        match self {
            Self::Configured(d) | Self::NodeFallback(d) => d,
        }
    }

    pub fn into_did(self) -> icn_identity::Did {
        match self {
            Self::Configured(d) | Self::NodeFallback(d) => d,
        }
    }

    pub fn is_configured(&self) -> bool {
        matches!(self, Self::Configured(_))
    }
}

#[cfg(test)]
mod treasury_resolution_tests {
    use super::*;

    fn node() -> icn_identity::Did {
        icn_identity::KeyPair::generate().unwrap().did().clone()
    }

    #[test]
    fn unset_falls_back_to_the_node_did() {
        let node = node();
        let resolved = CooperativeConfig::default()
            .resolve_treasury_did(&node)
            .unwrap();
        assert_eq!(resolved, TreasuryDid::NodeFallback(node.clone()));
        assert!(!resolved.is_configured());
        assert_eq!(resolved.did(), &node);
    }

    #[test]
    fn a_keypair_backed_treasury_is_used_and_marked_institutional() {
        let node = node();
        let treasury = icn_identity::KeyPair::generate().unwrap().did().clone();
        let cfg = CooperativeConfig {
            treasury_did: Some(treasury.as_str().to_string()),
            ..Default::default()
        };
        let resolved = cfg.resolve_treasury_did(&node).unwrap();
        assert!(resolved.is_configured());
        assert_eq!(resolved.did(), &treasury);
        assert_ne!(resolved.did(), &node);
    }

    /// The spelling the cooperative crate's `derive_treasury_did` produces. It is
    /// not multibase, so it never parses — and it used to become the node DID.
    #[test]
    fn the_legacy_treasury_label_spelling_is_refused_not_silently_replaced() {
        let node = node();
        let cfg = CooperativeConfig {
            treasury_did: Some("did:icn:treasury:3xY9mKp2QvL8nRt4".to_string()),
            ..Default::default()
        };
        let err = cfg
            .resolve_treasury_did(&node)
            .expect_err("an unusable treasury DID must refuse, not fall back");
        let msg = err.to_string();
        assert!(
            msg.contains("did:icn:treasury:3xY9mKp2QvL8nRt4"),
            "the refusal must name the offending value: {msg}"
        );
    }

    /// An anchor-derived DID whose padded bytes are not a valid Ed25519 point.
    /// This is the shape `Did::from_anchor_id` produces roughly half the time.
    #[test]
    fn an_unusable_anchor_derived_treasury_is_refused_not_silently_replaced() {
        let node = node();
        // Search for a sample that genuinely fails to parse, so the test is
        // about the refusal and not about a lucky constant.
        let mut unusable = None;
        for seed in 0u8..64 {
            let mut bytes = [0u8; 32];
            bytes[0] = seed;
            bytes[1] = seed.wrapping_mul(7).wrapping_add(3);
            let candidate = icn_identity::Did::from_anchor_id(&bytes);
            if candidate.as_str().parse::<icn_identity::Did>().is_err() {
                unusable = Some(candidate);
                break;
            }
        }
        let unusable = unusable.expect("an unparseable anchor-derived DID must exist");
        let cfg = CooperativeConfig {
            treasury_did: Some(unusable.as_str().to_string()),
            ..Default::default()
        };
        let err = cfg
            .resolve_treasury_did(&node)
            .expect_err("an anchor-derived DID that is not a valid Ed25519 point must refuse");
        assert!(
            !err.to_string().contains(node.as_str()),
            "the node DID must not appear as the resolved treasury"
        );
    }
}
