[package]
name = "icn-federation"
version = "0.1.0"
edition = "2021"
description = "Federation implementation for the ICN Runtime"

[dependencies]
# Use workspace dependencies where available
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
cid = { workspace = true, features = ["serde-codec"] }
multihash = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.3", features = ["v4", "serde"] }
rand = "0.8"
sha2 = "0.10"
base64 = "0.21"

# SSI dependencies
ssi-jwk = "0.1.2"

# ICN crates
icn-common = { path = "../common" }
icn-identity = { path = "../identity" }

# LibP2P dependencies
libp2p = { version = "0.53", features = ["tokio", "tcp", "noise", "yamux", "gossipsub", "mdns", "kad", "request-response", "macros", "identify", "serde", "json", "cbor"] }
libp2p-request-response = { version = "0.26", features = ["cbor"] }
tokio = { version = "1.35", features = ["sync", "rt-multi-thread", "time", "macros", "io-util"] }
futures = { version = "0.3", features = ["thread-pool"] }

# Dependencies that will be used in a future update for the debug API
# They are currently unused
axum = { version = "0.7", optional = true }
tower-http = { version = "0.5", optional = true, features = ["cors"] }
tower = { version = "0.4", optional = true }

[features]
default = ["testing"]  # Enable testing feature by default
testing = []  # Enable this for integration testing with HTTP debug API 

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
