apiVersion: v1
kind: Service
metadata:
  name: icn
  namespace: icn
  labels:
    app: icn
spec:
  type: ClusterIP
  selector:
    app: icn
    component: daemon
  ports:
  - name: quic
    port: 7777
    protocol: UDP
    targetPort: quic
  - name: rpc
    port: 5601
    protocol: TCP
    targetPort: rpc
  - name: metrics
    port: 9100
    protocol: TCP
    targetPort: metrics
  - name: gateway
    port: 8080
    protocol: TCP
    targetPort: gateway
---
apiVersion: v1
kind: Service
metadata:
  name: icn-nodeport
  namespace: icn
  labels:
    app: icn
spec:
  type: NodePort
  selector:
    app: icn
    component: daemon
  ports:
  - name: quic
    port: 7777
    protocol: UDP
    targetPort: quic
    nodePort: 30777
  - name: rpc
    port: 5601
    protocol: TCP
    targetPort: rpc
    nodePort: 30601
  - name: gateway
    port: 8080
    protocol: TCP
    targetPort: gateway
    nodePort: 30080

