[package]
name = "icn-networking"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
tendermint = "0.23"

[lib]
name = "icn_networking"
path = "src/lib.rs"
