[package]
name = "icn-models"
version = "0.1.0"
edition = "2021"
description = "Shared data models for the ICN Runtime"

[dependencies]
# Core dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
anyhow = "1.0"
async-trait = "0.1"

# IPLD and content-addressing
cid = { version = "0.10.1", features = ["serde"] }
multihash = { version = "0.16.3", features = ["sha2"] }
libipld = { version = "0.14", features = ["derive"] }
serde_ipld_dagcbor = "0.4"
serde_bytes = "0.11"

# ICN dependencies
icn-common = { path = "../icn-common" }
icn-identity = { path = "../icn-identity" }
