[package]
name = "icn-dag"
version = "0.1.0"
edition = "2021"
description = "DAG objects, Merkle anchoring, and Lineage for the ICN Runtime"

[dependencies]
icn-identity = { path = "../identity" }
merkle-cbt = { workspace = true }
multihash = { workspace = true }
cid = { workspace = true }
libipld = { workspace = true, features = ["derive"] }
serde_ipld_dagcbor = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
icn-storage = { path = "../storage" }
async-trait = { workspace = true }
lru = "0.11" 
sha2 = "0.10.9"
