refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} {h({l})} [{T}] {t} - {m}{n}"

  file:
    kind: file
    path: "log/icn.log"
    encoder:
      pattern: "{d} {l} [{T}] {t} - {m}{n}"

root:
  level: info
  appenders:
    - stdout
    - file

loggers:
  icn:
    level: debug
    appenders:
      - stdout
      - file
    additive: false
