/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the current health status of the Gateway API.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request authentication challenge
         * @description Request a challenge nonce for DID-based authentication.
         *     The challenge must be signed with the DID's private key and
         *     submitted to `/v1/auth/verify` within 5 minutes.
         */
        post: operations["requestChallenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify signature and get JWT token
         * @description Submit the signed challenge to receive a JWT token.
         *     The signature must be created using the Ed25519 private key
         *     corresponding to the DID's public key.
         */
        post: operations["verifyChallenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/coops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List cooperatives */
        get: operations["listCoops"];
        put?: never;
        /** Create a cooperative */
        post: operations["createCoop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/coops/{coop_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get cooperative details */
        get: operations["getCoop"];
        /** Update cooperative */
        put: operations["updateCoop"];
        post?: never;
        /** Delete cooperative */
        delete: operations["deleteCoop"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/coops/{coop_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List members */
        get: operations["listMembers"];
        put?: never;
        /** Add member */
        post: operations["addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/coops/{coop_id}/members/{did}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update member role */
        put: operations["updateMember"];
        post?: never;
        /** Remove member */
        delete: operations["removeMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledger/{coop_id}/balance/{did}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get balance */
        get: operations["getBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledger/{coop_id}/payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create payment
         * @description Create a mutual credit payment from the authenticated user to another member.
         */
        post: operations["createPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledger/{coop_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get transaction history */
        get: operations["getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gov/domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List governance domains */
        get: operations["listDomains"];
        put?: never;
        /** Create governance domain */
        post: operations["createDomain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gov/domains/{domain_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get governance domain */
        get: operations["getDomain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gov/domains/{domain_id}/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List proposals */
        get: operations["listProposals"];
        put?: never;
        /** Create proposal */
        post: operations["createProposal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gov/proposals/{proposal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get proposal */
        get: operations["getProposal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gov/proposals/{proposal_id}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open proposal for voting */
        post: operations["openProposal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gov/proposals/{proposal_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close proposal and calculate outcome */
        post: operations["closeProposal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gov/proposals/{proposal_id}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get vote tally */
        get: operations["getVoteTally"];
        put?: never;
        /** Cast vote */
        post: operations["castVote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ws/{coop_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * WebSocket event stream
         * @description Connect for real-time event streaming.
         *
         *     After connecting, send: `{"type": "Auth", "token": "..."}`
         *
         *     Events include: PaymentCreated, MemberAdded, MemberRemoved,
         *     RoleUpdated, SettingsUpdated, GovernanceDomainCreated,
         *     GovernanceProposalCreated, GovernanceProposalOpened,
         *     GovernanceProposalClosed, GovernanceVoteCast
         */
        get: operations["websocketConnect"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
            message: string;
        };
        HealthResponse: {
            /** @enum {string} */
            status?: "healthy" | "degraded" | "unhealthy";
            version?: string;
        };
        ChallengeRequest: {
            did: string;
        };
        ChallengeResponse: {
            challenge?: string;
            /** Format: date-time */
            expires_at?: string;
        };
        VerifyRequest: {
            did: string;
            signature: string;
            coop_id: string;
            scopes: string[];
        };
        TokenResponse: {
            token?: string;
            /** Format: date-time */
            expires_at?: string;
        };
        Cooperative: {
            id?: string;
            name?: string;
            description?: string;
            owner?: string;
            /** Format: date-time */
            created_at?: string;
        };
        CreateCoopRequest: {
            id: string;
            name: string;
            description?: string;
        };
        UpdateCoopRequest: {
            name?: string;
            description?: string;
        };
        Member: {
            did?: string;
            /** @enum {string} */
            role?: "owner" | "admin" | "member";
            /** Format: date-time */
            joined_at?: string;
        };
        AddMemberRequest: {
            did: string;
            /** @enum {string} */
            role: "admin" | "member";
        };
        UpdateMemberRequest: {
            role: string;
        };
        Balance: {
            did?: string;
            balance?: number;
            currency?: string;
        };
        PaymentRequest: {
            to: string;
            amount: number;
            currency: string;
            memo?: string;
        };
        Payment: {
            /** Format: uuid */
            id?: string;
            from?: string;
            to?: string;
            amount?: number;
            currency?: string;
            memo?: string;
            /** Format: date-time */
            created_at?: string;
        };
        Transaction: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            type?: "sent" | "received";
            amount?: number;
            currency?: string;
            counterparty?: string;
            memo?: string;
            /** Format: date-time */
            created_at?: string;
        };
        GovernanceDomain: {
            domain_id?: string;
            name?: string;
            description?: string;
            members?: string[];
            /** Format: date-time */
            created_at?: string;
        };
        CreateDomainRequest: {
            domain_id: string;
            name: string;
            description?: string;
            members: string[];
        };
        Proposal: {
            /** Format: uuid */
            id?: string;
            domain_id?: string;
            title?: string;
            description?: string;
            /** @enum {string} */
            kind?: "text" | "budget" | "membership" | "config_change";
            /** @enum {string} */
            state?: "draft" | "open" | "closed";
            author?: string;
            /** @enum {string} */
            outcome?: "accepted" | "rejected" | "no_quorum";
            /** Format: date-time */
            created_at?: string;
        };
        CreateProposalRequest: {
            title: string;
            description?: string;
            /** @enum {string} */
            kind: "text" | "budget" | "membership" | "config_change";
        };
        CastVoteRequest: {
            /** @enum {string} */
            choice: "for" | "against" | "abstain";
        };
        Vote: {
            /** Format: uuid */
            proposal_id?: string;
            voter?: string;
            /** @enum {string} */
            choice?: "for" | "against" | "abstain";
            /** Format: date-time */
            cast_at?: string;
        };
        VoteTally: {
            /** Format: uuid */
            proposal_id?: string;
            votes_for?: number;
            votes_against?: number;
            votes_abstain?: number;
            total_votes?: number;
            quorum_reached?: boolean;
        };
    };
    responses: {
        /** @description Invalid request parameters */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid authentication */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Insufficient permissions */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rate limit exceeded */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        CoopId: string;
        Did: string;
        DomainId: string;
        ProposalId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "healthy",
                     *       "version": "1.0.0"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    requestChallenge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "did": "did:icn:z6MkhaXgBZDvotDkL5257faiztiGiC2QtKLGpbnnEGta2doK"
                 *     }
                 */
                "application/json": components["schemas"]["ChallengeRequest"];
            };
        };
        responses: {
            /** @description Challenge created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "challenge": "a1b2c3d4e5f6...",
                     *       "expires_at": "2025-01-15T12:05:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["ChallengeResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    verifyChallenge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "did": "did:icn:z6MkhaXgBZDvotDkL5257faiztiGiC2QtKLGpbnnEGta2doK",
                 *       "signature": "base64-encoded-signature...",
                 *       "coop_id": "my-coop",
                 *       "scopes": [
                 *         "ledger:read",
                 *         "ledger:write",
                 *         "gov:read",
                 *         "gov:write"
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Authentication successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...",
                     *       "expires_at": "2025-01-16T12:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listCoops: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of cooperatives */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cooperative"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    createCoop: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCoopRequest"];
            };
        };
        responses: {
            /** @description Cooperative created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cooperative"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Cooperative ID already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["RateLimited"];
        };
    };
    getCoop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                coop_id: components["parameters"]["CoopId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cooperative details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cooperative"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    updateCoop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                coop_id: components["parameters"]["CoopId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCoopRequest"];
            };
        };
        responses: {
            /** @description Cooperative updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    deleteCoop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                coop_id: components["parameters"]["CoopId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cooperative deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                coop_id: components["parameters"]["CoopId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    addMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                coop_id: components["parameters"]["CoopId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberRequest"];
            };
        };
        responses: {
            /** @description Member added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Member already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["RateLimited"];
        };
    };
    updateMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                coop_id: components["parameters"]["CoopId"];
                did: components["parameters"]["Did"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberRequest"];
            };
        };
        responses: {
            /** @description Member updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                coop_id: components["parameters"]["CoopId"];
                did: components["parameters"]["Did"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    getBalance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                coop_id: components["parameters"]["CoopId"];
                did: components["parameters"]["Did"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Balance retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Balance"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    createPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                coop_id: components["parameters"]["CoopId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentRequest"];
            };
        };
        responses: {
            /** @description Payment created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Insufficient balance or credit limit exceeded */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["RateLimited"];
        };
    };
    getHistory: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                coop_id: components["parameters"]["CoopId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    listDomains: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of domains */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GovernanceDomain"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    createDomain: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDomainRequest"];
            };
        };
        responses: {
            /** @description Domain created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GovernanceDomain"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Domain ID already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["RateLimited"];
        };
    };
    getDomain: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain_id: components["parameters"]["DomainId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Domain details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GovernanceDomain"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    listProposals: {
        parameters: {
            query?: {
                state?: "draft" | "open" | "closed";
            };
            header?: never;
            path: {
                domain_id: components["parameters"]["DomainId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of proposals */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    createProposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain_id: components["parameters"]["DomainId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProposalRequest"];
            };
        };
        responses: {
            /** @description Proposal created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    getProposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: components["parameters"]["ProposalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proposal details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    openProposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: components["parameters"]["ProposalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proposal opened */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Proposal is not in Draft state */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    closeProposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: components["parameters"]["ProposalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proposal closed with outcome */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Proposal is not in Open state */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    getVoteTally: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: components["parameters"]["ProposalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vote tally */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoteTally"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    castVote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: components["parameters"]["ProposalId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CastVoteRequest"];
            };
        };
        responses: {
            /** @description Vote cast */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vote"];
                };
            };
            /** @description Proposal is not open for voting */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    websocketConnect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                coop_id: components["parameters"]["CoopId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching to WebSocket protocol */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
        };
    };
}
