# ICN Wallet Configuration

# Federation sync configuration
[sync]
# Federation node URLs to connect to
federation_urls = [
    "http://localhost:8080",
    "http://backup-federation.example.com"
]

# Sync interval in seconds
sync_interval_seconds = 3600

# HTTP request timeout in seconds
request_timeout_seconds = 30

# Maximum number of retry attempts for HTTP requests
max_retry_attempts = 3

# Whether to auto-sync on startup
auto_sync_on_startup = true

# Whether to auto-sync periodically
auto_sync_periodic = true

# Storage paths configuration
[storage]
# Base path for wallet data
base_path = "./storage"

# Path for sync data
sync_state_path = "./storage/sync"

# Logging configuration
[logging]
# Log level: "trace", "debug", "info", "warn", "error"
level = "info"

# Whether to log to file
log_to_file = true

# Log file path
log_file = "./logs/wallet.log" 