[package]
name = "mesh-types"
version = "0.1.0"
edition = "2021"
description = "Core types for ICN Mesh Compute overlay"
license = "MIT OR Apache-2.0"

[dependencies]
# Core dependencies
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
anyhow = { workspace = true }
async-trait = { workspace = true }

# ICN dependencies
icn-identity = { path = "../../../icn-runtime-root/crates/icn-identity" }
icn-common = { path = "../../../icn-runtime-root/crates/icn-common" }

# IPLD and content addressing
cid = { workspace = true }
multihash = { workspace = true }

# Cryptography
sha2 = { workspace = true }
ed25519-dalek = "1.0"

[dev-dependencies]
tokio-test = "0.4"
