[package]
name = "icn-p2p"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
serde = "1.0"
tokio-tungstenite = "0.15"
warp = "0.3"
futures-util = "0.3"
