[package]
name = "icn-p2p"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
tokio-tungstenite = "0.26"
warp = "0.3"
futures-util = "0.3"
icn-types = { path = "../icn-types" }
chacha20poly1305 = "0.9"
blake3 = "1.0"
rand = "0.8"
x25519-dalek = "2.0"  # Updated to v2.0 which uses newer zeroize
bincode = "1.3"
