[package]
name = "icn-wallet-sync"
version = "0.1.0"
edition = "2021"
description = "ICN Wallet synchronization module"

[dependencies]
# Core wallet components
icn-wallet-types = { path = "../icn-wallet-types" }

# Async and futures
tokio = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }

# Error handling and logging
thiserror = { workspace = true }
tracing = { workspace = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }

# Network and HTTP
reqwest = { workspace = true }
backoff = { workspace = true, features = ["futures"] }

# Crypto and hashes
cid = { workspace = true }
multihash = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
hex = { workspace = true }
sha2 = { workspace = true }
base64 = { workspace = true }

[dev-dependencies]
tokio-test = "0.4"
mockito = "1.0"
test-log = "0.2" 
