[package]
name = "icn-wallet-identity"
version = "0.1.0"
edition = "2021"
description = "Identity management for the ICN Wallet"
license = "MIT OR Apache-2.0"

[dependencies]
# Workspace dependencies
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
ed25519-dalek = { workspace = true }
sha2 = { workspace = true }
base64 = { workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
# Required for generating random seeds for ed25519
getrandom = "0.2"

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.8" 