[package]
name = "agoranet-api"
version = "0.1.0"
edition = "2021"
description = "RESTful API for AgoraNet deliberation layer"

[dependencies]
# Use workspace dependencies where available
axum = { workspace = true }
tokio = { workspace = true, features = ["full"] }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true, features = ["trace", "cors"] }
uuid = { workspace = true, features = ["v4", "serde"] }

# Additional dependencies
sqlx = { workspace = true, optional = true }

[features]
default = []
database = ["sqlx"]
