[package]
name = "icn-wallet-actions"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.3", features = ["v4", "serde"] }

# Optional workspace dependencies
icn-wallet-storage = { version = "0.1.0", path = "../icn-wallet-storage", optional = true }
icn-wallet-types = { version = "0.1.0", path = "../icn-wallet-types", optional = true }

[features]
default = []
storage = ["icn-wallet-storage"]
types = ["icn-wallet-types"] 