[package]
name = "icn-governance"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
sled.workspace = true
anyhow.workspace = true
async-trait = "0.1"
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"
icn-entity = { path = "../icn-entity" }
icn-identity = { path = "../icn-identity" }
icn-obs = { path = "../icn-obs" }
icn-trust = { path = "../icn-trust" }
icn-time.workspace = true
thiserror.workspace = true
tokio = { workspace = true }
uuid = { version = "1.0", features = ["v4", "serde"] }
sha2.workspace = true
hex = "0.4"
lru = "0.12"
tracing.workspace = true

[dev-dependencies]
icn-store = { path = "../icn-store" }
tempfile = "3"

[lints]
workspace = true
