apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: icn-data-pvc
  namespace: icn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
