[package]
name = "icn-core-vm"
version = "0.1.0"
edition = "2021"
description = "Secure WASM Virtual Machine Runtime for the ICN"

[dependencies]
icn-identity = { path = "../identity" }
icn-storage = { path = "../storage" }
icn-dag = { path = "../dag" }
icn-economics = { path = "../economics" }
wasmtime = "12.0.2"
thiserror = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
cid = { workspace = true }
futures = { workspace = true }
chrono = "0.4"
wat = "1.0"
log = "0.4"
multihash = { workspace = true }
tokio = { version = "1.0", features = ["sync", "rt-multi-thread", "macros"] }
uuid = { version = "1.3", features = ["v4", "serde"] }

[dev-dependencies]
tokio = { version = "1.0", features = ["sync", "rt-multi-thread", "macros"] }

[features]
default = []
wasmtime-4 = []  # Feature flag for older wasmtime 4.x compatibility 