[package]
name = "icn-core-vm"
version = "0.1.0"
edition = "2021"
description = "Secure WASM Virtual Machine Runtime for the ICN"

[dependencies]
icn-common = { path = "../../common/icn-common" }
icn-identity = { path = "../icn-identity" }
icn-storage = { path = "../icn-storage" }
icn-dag = { path = "../icn-dag" }
icn-economics = { path = "../icn-economics" }
icn-models = { path = "../icn-models" }
icn-wallet-sync = { path = "../../wallet/icn-wallet-sync" }
wasmtime = "12.0.2"
thiserror = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_ipld_dagcbor = { workspace = true }
async-trait = { workspace = true }
cid = { workspace = true }
futures = { workspace = true }
chrono = "0.4"
wat = "1.0"
log = "0.4"
multihash = { workspace = true }
tokio = { version = "1.0", features = ["sync", "rt-multi-thread", "macros"] }
uuid = { version = "1.3", features = ["v4", "serde"] }
libipld = { workspace = true }
prometheus = { version = "0.13", features = ["process"] }
once_cell = "1.18"
hex = "0.4.3"
sha2 = "0.10.7"

[dev-dependencies]
tokio = { version = "1.0", features = ["sync", "rt-multi-thread", "macros"] }

[features]
default = []
wasmtime-4 = []  # Feature flag for older wasmtime 4.x compatibility 