[package]
name = "icn-runtime-bin"
version = "0.1.0"
edition = "2021"
description = "Placeholder package for ICN Runtime bin directory"

[lib]
name = "icn_runtime_bin"
path = "bin_lib.rs"
crate-type = ["lib"]

[dependencies]
# No dependencies needed for this placeholder 