[package]
name = "icn-types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.9"
chrono = "0.4"
tokio = { version = "1", features = ["full"] }
