#!/usr/bin/env bash
# build-image.sh
#
# ICN appliance image builder.
#
# Two modes:
#   --dry-run   Print the planned steps and exit. No mutation.
#   --real      Build a real local dev QCOW2 image from a staged Debian
#               cloud base image, plus a manifest JSON. Requires required
#               tools and environment variables.
#
# Required for --real:
#   ICN_APPLIANCE_BASE_IMAGE     Path to a staged Debian cloud base image.
#                                Operator stages this manually; this script
#                                does NOT download anything.
#   ICN_APPLIANCE_OUTPUT_DIR     Directory the built image is written to.
#   ICN_APPLIANCE_VERSION        Version label baked into the manifest JSON.
#
# Optional:
#   ICN_APPLIANCE_BASE_SHA256    If set, verify the base image checksum.
#   ICN_APPLIANCE_IMAGE_FORMAT   qcow2 (default) | raw
#   ICN_APPLIANCE_ARCH           amd64 (default)
#   ICN_APPLIANCE_IMAGE_NAME     Override the output basename.
#
# Required tools for --real:
#   qemu-img, virt-customize, virt-sysprep, sha256sum, cargo
#
# This builder does NOT:
#   - Download external files. The base image must be staged locally.
#   - Embed secrets. JWT and keystore passphrase are generated by the
#     image's firstboot service on first boot, NOT here.
#   - Use devnet-insecure credentials.
#   - Produce a signed release. The output is a local dev image.
#
# Honest non-claims:
#   The image this script produces is NOT production. It is unsigned, not
#   immutable, and not a partner-distributable artifact. See
#   docs/architecture/DEBIAN_APPLIANCE_MODEL.md.

set -euo pipefail

MODE="dry-run"

log()  { printf '[build-image] %s\n' "$*"; }
warn() { printf '[build-image] WARN: %s\n' "$*" >&2; }
err()  { printf '[build-image] ERROR: %s\n' "$*" >&2; }

usage() {
    sed -n '2,40p' "$0"
    exit 0
}

while [ "$#" -gt 0 ]; do
    case "$1" in
        --dry-run) MODE="dry-run" ; shift ;;
        --real)    MODE="real"    ; shift ;;
        --help|-h) usage ;;
        *)
            err "unknown argument: $1"
            exit 2
            ;;
    esac
done

# ---------- common context ----------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APPLIANCE_DIR="$SCRIPT_DIR"
DEPLOY_DIR="$(cd "$APPLIANCE_DIR/.." && pwd)"
REPO_ROOT="$(cd "$DEPLOY_DIR/.." && pwd)"

ARCH="${ICN_APPLIANCE_ARCH:-amd64}"
IMAGE_FORMAT="${ICN_APPLIANCE_IMAGE_FORMAT:-qcow2}"

log "Mode: $MODE"
log "Repo root:        $REPO_ROOT"
log "Appliance dir:    $APPLIANCE_DIR"
log "Arch:             $ARCH"
log "Image format:     $IMAGE_FORMAT"
log "Base image:       ${ICN_APPLIANCE_BASE_IMAGE:-<unset>}"
log "Version:          ${ICN_APPLIANCE_VERSION:-<unset>}"
log "Output dir:       ${ICN_APPLIANCE_OUTPUT_DIR:-<unset>}"
log "Base SHA256:      ${ICN_APPLIANCE_BASE_SHA256:-<not set; will not verify>}"
echo

# ---------- dry-run plan (printed in both modes for transparency) ----------
print_plan() {
cat <<'EOF_PLAN'
[build-image] Planned build steps:

  1) Validate required tools: qemu-img, virt-customize, virt-sysprep, sha256sum, cargo.
  2) Validate the staged base image exists; verify SHA256 if provided.
  3) Build release binaries:
       cd icn && cargo build --release -p icnd -p icnctl
  4) Copy the base image into the output dir as the working image.
  5) virt-customize the working image:
       - apt install ca-certificates curl openssl python3 systemd
       - mkdir /etc/icn /var/lib/icn /var/log/icn /usr/share/icn/static /etc/icn/roles
       - copy icnd, icnctl  -> /usr/local/bin/
       - copy deploy/icnd.service                                   -> /etc/systemd/system/
       - copy deploy/appliance/systemd/icn-appliance-firstboot.service -> /etc/systemd/system/
       - copy deploy/appliance/scripts/icn-appliance-firstboot.sh   -> /usr/local/sbin/
       - copy deploy/appliance/appliance.manifest.example.yaml      -> /etc/icn/
       - copy deploy/appliance/roles/*.example.yaml                 -> /etc/icn/roles/
       - chmod +x on the binaries and the firstboot script
       - systemctl enable icn-appliance-firstboot.service icnd.service
       - truncate /etc/machine-id so each booted instance gets its own
  6) virt-sysprep the working image to scrub instance state (machine-id,
     logfiles, bash-history, tmp-files).
  7) Convert to the requested format (qcow2 or raw).
  8) Compute output SHA256.
  9) Emit a manifest JSON next to the image with version, hashes, git
     commit, build timestamp, and an explicit non-production flag.
EOF_PLAN
}

print_plan

# ---------- dry-run exit ----------
if [ "$MODE" = "dry-run" ]; then
    log "Exiting cleanly. No image was built."
    exit 0
fi

# ---------- --real path ----------

# Required env vars
require_env() {
    local name="$1"
    if [ -z "${!name:-}" ]; then
        err "$name is required for --real. See script header."
        exit 2
    fi
}
require_env ICN_APPLIANCE_BASE_IMAGE
require_env ICN_APPLIANCE_OUTPUT_DIR
require_env ICN_APPLIANCE_VERSION

# Required tools
require_tool() {
    local t="$1"
    if ! command -v "$t" >/dev/null 2>&1; then
        err "required tool not found on PATH: $t"
        return 1
    fi
}
MISSING=0
for t in qemu-img virt-customize virt-sysprep sha256sum cargo; do
    if ! require_tool "$t"; then
        MISSING=1
    fi
done
if [ "$MISSING" -ne 0 ]; then
    err "One or more required tools missing. On Debian/Ubuntu, typical packages:"
    err "  qemu-img         -> qemu-utils"
    err "  virt-customize   -> libguestfs-tools"
    err "  virt-sysprep     -> libguestfs-tools"
    err "  sha256sum        -> coreutils"
    err "  cargo            -> rustup or rust-toolchain"
    exit 3
fi

# Validate base image
if [ ! -f "$ICN_APPLIANCE_BASE_IMAGE" ]; then
    err "Base image not found at: $ICN_APPLIANCE_BASE_IMAGE"
    err "Stage a Debian cloud image manually (e.g. debian-12-genericcloud-amd64.qcow2)."
    exit 4
fi
log "Base image present: $ICN_APPLIANCE_BASE_IMAGE"

if [ -n "${ICN_APPLIANCE_BASE_SHA256:-}" ]; then
    log "Verifying base image SHA256..."
    actual="$(sha256sum "$ICN_APPLIANCE_BASE_IMAGE" | awk '{print $1}')"
    if [ "$actual" != "$ICN_APPLIANCE_BASE_SHA256" ]; then
        err "Base image SHA256 mismatch:"
        err "  expected: $ICN_APPLIANCE_BASE_SHA256"
        err "  actual:   $actual"
        exit 5
    fi
    log "Base image SHA256 verified."
else
    warn "ICN_APPLIANCE_BASE_SHA256 not set; skipping base image checksum verification."
fi

# Ensure output dir
mkdir -p "$ICN_APPLIANCE_OUTPUT_DIR"
IMAGE_NAME="${ICN_APPLIANCE_IMAGE_NAME:-icn-appliance-${ICN_APPLIANCE_VERSION}-${ARCH}.${IMAGE_FORMAT}}"
OUT_IMAGE="$ICN_APPLIANCE_OUTPUT_DIR/$IMAGE_NAME"
OUT_MANIFEST="${OUT_IMAGE%.*}.manifest.json"

log "Output image:    $OUT_IMAGE"
log "Output manifest: $OUT_MANIFEST"

# Build release binaries
log "Building release binaries (cargo build --release -p icnd -p icnctl)..."
(
    cd "$REPO_ROOT/icn"
    cargo build --release -p icnd -p icnctl
)
ICND_BIN="$REPO_ROOT/icn/target/release/icnd"
ICNCTL_BIN="$REPO_ROOT/icn/target/release/icnctl"
HEALTH_CHECK_BIN="$DEPLOY_DIR/health-check.sh"
for f in "$ICND_BIN" "$ICNCTL_BIN"; do
    if [ ! -f "$f" ]; then
        err "Expected binary missing after build: $f"
        exit 6
    fi
done
log "Built: $ICND_BIN"
log "Built: $ICNCTL_BIN"

ICND_SHA256="$(sha256sum "$ICND_BIN"   | awk '{print $1}')"
ICNCTL_SHA256="$(sha256sum "$ICNCTL_BIN" | awk '{print $1}')"

# Copy base image to working path
log "Copying base image -> working image (qemu-img convert)..."
qemu-img convert -O "$IMAGE_FORMAT" "$ICN_APPLIANCE_BASE_IMAGE" "$OUT_IMAGE"
log "Working image at: $OUT_IMAGE"

# Determine which optional sources are present (role examples, firstboot,
# manifest example, icnd.service, smoke-only nothing).
ROLE_EXAMPLES=( "$APPLIANCE_DIR/roles/"*.example.yaml )
APPLIANCE_MANIFEST_EXAMPLE="$APPLIANCE_DIR/appliance.manifest.example.yaml"
FIRSTBOOT_SCRIPT="$APPLIANCE_DIR/scripts/icn-appliance-firstboot.sh"
FIRSTBOOT_UNIT="$APPLIANCE_DIR/systemd/icn-appliance-firstboot.service"
ICND_SERVICE="$DEPLOY_DIR/icnd.service"

for f in "$FIRSTBOOT_SCRIPT" "$FIRSTBOOT_UNIT" "$ICND_SERVICE" "$APPLIANCE_MANIFEST_EXAMPLE"; do
    if [ ! -f "$f" ]; then
        err "Expected source file missing: $f"
        exit 7
    fi
done

# virt-customize the image
log "Running virt-customize on $OUT_IMAGE ..."
VIRT_CUSTOMIZE_ARGS=(
    -a "$OUT_IMAGE"
    --update
    --install "ca-certificates,curl,openssl,python3,systemd,sudo"

    --mkdir /etc/icn
    --mkdir /etc/icn/roles
    --mkdir /var/lib/icn
    --mkdir /var/log/icn
    --mkdir /usr/share/icn
    --mkdir /usr/share/icn/static

    --copy-in "$ICND_BIN:/usr/local/bin"
    --copy-in "$ICNCTL_BIN:/usr/local/bin"
    --run-command "chmod +x /usr/local/bin/icnd /usr/local/bin/icnctl"

    --copy-in "$ICND_SERVICE:/etc/systemd/system"
    --copy-in "$FIRSTBOOT_UNIT:/etc/systemd/system"

    --copy-in "$FIRSTBOOT_SCRIPT:/usr/local/sbin"
    --run-command "chmod +x /usr/local/sbin/icn-appliance-firstboot.sh"
    --run-command "ln -sf /usr/local/sbin/icn-appliance-firstboot.sh /usr/local/sbin/icn-appliance-firstboot"

    --copy-in "$APPLIANCE_MANIFEST_EXAMPLE:/etc/icn"

    --run-command "useradd --system --home-dir /var/lib/icn --shell /bin/false icn || true"
    --run-command "chown -R icn:icn /var/lib/icn /var/log/icn"

    --run-command "systemctl enable icn-appliance-firstboot.service"
    --run-command "systemctl enable icnd.service"
)
# Role examples (only if at least one matches the glob)
if [ -f "${ROLE_EXAMPLES[0]:-/nonexistent}" ]; then
    for r in "${ROLE_EXAMPLES[@]}"; do
        VIRT_CUSTOMIZE_ARGS+=( --copy-in "$r:/etc/icn/roles" )
    done
fi

# Optional health-check helper if the existing script is present
if [ -f "$HEALTH_CHECK_BIN" ]; then
    VIRT_CUSTOMIZE_ARGS+=(
        --copy-in "$HEALTH_CHECK_BIN:/usr/local/bin"
        --run-command "mv /usr/local/bin/$(basename "$HEALTH_CHECK_BIN") /usr/local/bin/icn-health-check"
        --run-command "chmod +x /usr/local/bin/icn-health-check"
    )
fi

virt-customize "${VIRT_CUSTOMIZE_ARGS[@]}"

# virt-sysprep to scrub instance-specific state. --operations chosen
# narrowly so we don't accidentally wipe what we just installed.
log "Running virt-sysprep (machine-id, logfiles, bash-history, tmp-files)..."
virt-sysprep -a "$OUT_IMAGE" \
    --operations machine-id,logfiles,bash-history,tmp-files

# Final hash + manifest
log "Hashing output image..."
OUT_SHA256="$(sha256sum "$OUT_IMAGE" | awk '{print $1}')"

GIT_COMMIT="$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null || echo unknown)"
BUILD_TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

log "Writing manifest JSON: $OUT_MANIFEST"
cat > "$OUT_MANIFEST" <<EOF_MANIFEST
{
  "appliance_id": "icn-appliance-dev",
  "version": "${ICN_APPLIANCE_VERSION}",
  "arch": "${ARCH}",
  "image_format": "${IMAGE_FORMAT}",
  "image_path": "${OUT_IMAGE}",
  "image_sha256": "${OUT_SHA256}",
  "base_image_path": "${ICN_APPLIANCE_BASE_IMAGE}",
  "base_image_sha256": "${ICN_APPLIANCE_BASE_SHA256:-unset}",
  "git_commit": "${GIT_COMMIT}",
  "build_timestamp_utc": "${BUILD_TS}",
  "built_binaries": [
    { "path": "/usr/local/bin/icnd",   "source": "icn/target/release/icnd",   "sha256": "${ICND_SHA256}" },
    { "path": "/usr/local/bin/icnctl", "source": "icn/target/release/icnctl", "sha256": "${ICNCTL_SHA256}" }
  ],
  "non_production": true,
  "signed": false,
  "immutable": false,
  "notes": [
    "Local dev appliance image. NOT a signed release.",
    "Contains no embedded secrets; per-instance JWT and keystore passphrase",
    "are generated by icn-appliance-firstboot.service on first boot."
  ]
}
EOF_MANIFEST

log "DONE."
log "  Image:    $OUT_IMAGE"
log "  SHA256:   $OUT_SHA256"
log "  Manifest: $OUT_MANIFEST"
echo
log "Next: boot with deploy/appliance/smoke/smoke-local.sh --real"
log "      ICN_APPLIANCE_IMAGE=$OUT_IMAGE ICN_APPLIANCE_SSH_KEY=... bash deploy/appliance/smoke/smoke-local.sh --real"
