#!/usr/bin/env bash
# build-image.sh
#
# ICN appliance image builder.
#
# Two modes:
#   --dry-run   Print the planned steps and exit. No mutation.
#   --real      Build a real local dev QCOW2 image from a staged Debian
#               cloud base image, plus a manifest JSON. Requires required
#               tools and environment variables.
#
# Required for --real:
#   ICN_APPLIANCE_BASE_IMAGE     Path to a staged Debian cloud base image.
#                                Operator stages this manually; this script
#                                does NOT download anything.
#   ICN_APPLIANCE_OUTPUT_DIR     Directory the built image is written to.
#   ICN_APPLIANCE_VERSION        Version label baked into the manifest JSON.
#
# Optional:
#   ICN_APPLIANCE_BASE_SHA256    If set, verify the base image checksum.
#   ICN_APPLIANCE_IMAGE_FORMAT   qcow2 (default) | raw
#   ICN_APPLIANCE_ARCH           amd64 (default)
#   ICN_APPLIANCE_IMAGE_NAME     Override the output basename.
#   ICN_APPLIANCE_DEMO_PROFILE   1 = additionally install the DEV/DEMO
#                                profile: member-shell static payload +
#                                serving unit (:8090), demo env drop-in for
#                                icnd (0.0.0.0:8080 bind, dev gates, CORS),
#                                in-image icn-demo-seed / icn-demo-verify /
#                                icn-demo-reset, the NYCN fixture
#                                institution package, and the bundled 13/13
#                                receipt-chain rehearsal. Demo images are
#                                labeled in the manifest (demo_profile:
#                                true) and remain non-production dev
#                                artifacts. Default 0 (base image only).
#
# Required tools for --real:
#   qemu-img, virt-customize, virt-sysprep, sha256sum, cargo
#
# This builder does NOT:
#   - Download the base image. The base image must be staged locally at
#     ICN_APPLIANCE_BASE_IMAGE; this script never fetches it. (The
#     `--real` path DOES run `virt-customize --update --install ...`
#     under the hood, which fetches Debian apt packages over the network
#     from the base image's configured repos. That is an in-image apt
#     operation, not something this script reaches out for directly.)
#   - Embed secrets. JWT and keystore passphrase are generated by the
#     image's firstboot service on first boot, NOT here.
#   - Use devnet-insecure credentials.
#   - Produce a signed release. The output is a local dev image.
#
# Honest non-claims:
#   The image this script produces is NOT production. It is unsigned, not
#   immutable, and not a partner-distributable artifact. See
#   docs/architecture/DEBIAN_APPLIANCE_MODEL.md.

set -euo pipefail

MODE="dry-run"

log()  { printf '[build-image] %s\n' "$*"; }
warn() { printf '[build-image] WARN: %s\n' "$*" >&2; }
err()  { printf '[build-image] ERROR: %s\n' "$*" >&2; }

usage() {
    sed -n '2,40p' "$0"
    exit 0
}

while [ "$#" -gt 0 ]; do
    case "$1" in
        --dry-run) MODE="dry-run" ; shift ;;
        --real)    MODE="real"    ; shift ;;
        --help|-h) usage ;;
        *)
            err "unknown argument: $1"
            exit 2
            ;;
    esac
done

# ---------- common context ----------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APPLIANCE_DIR="$SCRIPT_DIR"
DEPLOY_DIR="$(cd "$APPLIANCE_DIR/.." && pwd)"
REPO_ROOT="$(cd "$DEPLOY_DIR/.." && pwd)"

ARCH="${ICN_APPLIANCE_ARCH:-amd64}"
IMAGE_FORMAT="${ICN_APPLIANCE_IMAGE_FORMAT:-qcow2}"
DEMO_PROFILE="${ICN_APPLIANCE_DEMO_PROFILE:-0}"

log "Mode: $MODE"
log "Repo root:        $REPO_ROOT"
log "Appliance dir:    $APPLIANCE_DIR"
log "Arch:             $ARCH"
log "Image format:     $IMAGE_FORMAT"
log "Base image:       ${ICN_APPLIANCE_BASE_IMAGE:-<unset>}"
log "Version:          ${ICN_APPLIANCE_VERSION:-<unset>}"
log "Output dir:       ${ICN_APPLIANCE_OUTPUT_DIR:-<unset>}"
log "Base SHA256:      ${ICN_APPLIANCE_BASE_SHA256:-<not set; will not verify>}"
log "Demo profile:     $DEMO_PROFILE (1 = DEV/DEMO payload + units installed)"
echo

# ---------- dry-run plan (printed in both modes for transparency) ----------
print_plan() {
cat <<'EOF_PLAN'
[build-image] Planned build steps:

  1) Validate required tools: qemu-img, virt-customize, virt-sysprep, sha256sum, cargo.
  2) Validate the staged base image exists; verify SHA256 if provided.
  3) Build release binaries:
       cd icn && cargo build --release -p icnd -p icnctl
  4) Copy the base image into the output dir as the working image.
  5) virt-customize the working image:
       - apt install ca-certificates curl openssl python3 systemd
       - mkdir /etc/icn /var/lib/icn /var/log/icn /usr/share/icn/static /etc/icn/roles
       - copy icnd, icnctl  -> /usr/local/bin/
       - copy deploy/icnd.service                                   -> /etc/systemd/system/
       - copy deploy/appliance/systemd/icn-appliance-firstboot.service -> /etc/systemd/system/
       - copy deploy/appliance/scripts/icn-appliance-firstboot.sh   -> /usr/local/sbin/
       - copy deploy/appliance/appliance.manifest.example.yaml      -> /etc/icn/
       - copy deploy/appliance/roles/*.example.yaml                 -> /etc/icn/roles/
       - chmod +x on the binaries and the firstboot script
       - systemctl enable icn-appliance-firstboot.service icnd.service
       - truncate /etc/machine-id so each booted instance gets its own
  6) virt-sysprep the working image to scrub instance state (machine-id,
     logfiles, bash-history, tmp-files).
  7) Convert to the requested format (qcow2 or raw).
  8) Compute output SHA256 (for the build-log summary).
  9) Emit a typed appliance manifest JSON next to the image via
       icnctl appliance emit-manifest
     (Rust-owned: streams SHA-256 over the image, base image, and each built
     binary; records git commit, build timestamp, and the honest
     non-production posture), then re-verify it with
       icnctl appliance verify-manifest --root <repo root>
     (fail-closed: re-hashes every artifact and rejects posture contradictions).

  When ICN_APPLIANCE_DEMO_PROFILE=1, step 5 additionally (DEV/DEMO only):
       - copy web/member-shell + web/pilot-ui/fixtures -> /usr/share/icn/static/web/
       - copy institutions/ (NYCN fixture package)     -> /usr/share/icn/demo/institutions/
       - copy 13/13 rehearsal scripts + evidence validator + nycn-dogfood kit
                                                        -> /usr/share/icn/demo/repo/
       - copy icn-member-shell.service + icn-demo-session.service -> /etc/systemd/system/
       - copy icnd.service.d/20-demo-profile.conf       -> /etc/systemd/system/icnd.service.d/
       - copy icn-demo-{seed,verify,reset}.sh + icn-demo-session.py -> /usr/local/sbin/
       - systemctl enable icn-member-shell.service icn-demo-session.service
       - mark manifest demo_profile: true
EOF_PLAN
}

print_plan

# ---------- dry-run exit ----------
if [ "$MODE" = "dry-run" ]; then
    log "Exiting cleanly. No image was built."
    exit 0
fi

# ---------- --real path ----------

# Required env vars
require_env() {
    local name="$1"
    if [ -z "${!name:-}" ]; then
        err "$name is required for --real. See script header."
        exit 2
    fi
}
require_env ICN_APPLIANCE_BASE_IMAGE
require_env ICN_APPLIANCE_OUTPUT_DIR
require_env ICN_APPLIANCE_VERSION

# Required tools
require_tool() {
    local t="$1"
    if ! command -v "$t" >/dev/null 2>&1; then
        err "required tool not found on PATH: $t"
        return 1
    fi
}
MISSING=0
for t in qemu-img virt-customize virt-sysprep sha256sum cargo; do
    if ! require_tool "$t"; then
        MISSING=1
    fi
done
if [ "$MISSING" -ne 0 ]; then
    err "One or more required tools missing. On Debian/Ubuntu, typical packages:"
    err "  qemu-img         -> qemu-utils"
    err "  virt-customize   -> libguestfs-tools"
    err "  virt-sysprep     -> libguestfs-tools"
    err "  sha256sum        -> coreutils"
    err "  cargo            -> rustup or rust-toolchain"
    exit 3
fi

# Validate base image
if [ ! -f "$ICN_APPLIANCE_BASE_IMAGE" ]; then
    err "Base image not found at: $ICN_APPLIANCE_BASE_IMAGE"
    err "Stage a Debian cloud image manually (e.g. debian-12-genericcloud-amd64.qcow2)."
    exit 4
fi
log "Base image present: $ICN_APPLIANCE_BASE_IMAGE"

if [ -n "${ICN_APPLIANCE_BASE_SHA256:-}" ]; then
    log "Verifying base image SHA256..."
    actual="$(sha256sum "$ICN_APPLIANCE_BASE_IMAGE" | awk '{print $1}')"
    if [ "$actual" != "$ICN_APPLIANCE_BASE_SHA256" ]; then
        err "Base image SHA256 mismatch:"
        err "  expected: $ICN_APPLIANCE_BASE_SHA256"
        err "  actual:   $actual"
        exit 5
    fi
    log "Base image SHA256 verified."
else
    warn "ICN_APPLIANCE_BASE_SHA256 not set; skipping base image checksum verification."
fi

# Ensure output dir
mkdir -p "$ICN_APPLIANCE_OUTPUT_DIR"
IMAGE_NAME="${ICN_APPLIANCE_IMAGE_NAME:-icn-appliance-${ICN_APPLIANCE_VERSION}-${ARCH}.${IMAGE_FORMAT}}"
OUT_IMAGE="$ICN_APPLIANCE_OUTPUT_DIR/$IMAGE_NAME"
OUT_MANIFEST="${OUT_IMAGE%.*}.manifest.json"

log "Output image:    $OUT_IMAGE"
log "Output manifest: $OUT_MANIFEST"

# Build release binaries
log "Building release binaries (cargo build --release -p icnd -p icnctl)..."
(
    cd "$REPO_ROOT/icn"
    cargo build --release -p icnd -p icnctl
)
ICND_BIN="$REPO_ROOT/icn/target/release/icnd"
ICNCTL_BIN="$REPO_ROOT/icn/target/release/icnctl"
HEALTH_CHECK_BIN="$DEPLOY_DIR/health-check.sh"
for f in "$ICND_BIN" "$ICNCTL_BIN"; do
    if [ ! -f "$f" ]; then
        err "Expected binary missing after build: $f"
        exit 6
    fi
done
log "Built: $ICND_BIN"
log "Built: $ICNCTL_BIN"
# Binary content hashes are computed by `icnctl appliance emit-manifest` below
# (it streams SHA-256 over each --binary FILE), so the script no longer hashes
# them here.

# Copy base image to working path
log "Copying base image -> working image (qemu-img convert)..."
qemu-img convert -O "$IMAGE_FORMAT" "$ICN_APPLIANCE_BASE_IMAGE" "$OUT_IMAGE"
log "Working image at: $OUT_IMAGE"

# Determine which optional sources are present (role examples, firstboot,
# manifest example, icnd.service, smoke-only nothing).
ROLE_EXAMPLES=( "$APPLIANCE_DIR/roles/"*.example.yaml )
APPLIANCE_MANIFEST_EXAMPLE="$APPLIANCE_DIR/appliance.manifest.example.yaml"
FIRSTBOOT_SCRIPT="$APPLIANCE_DIR/scripts/icn-appliance-firstboot.sh"
FIRSTBOOT_UNIT="$APPLIANCE_DIR/systemd/icn-appliance-firstboot.service"
ICND_SERVICE="$DEPLOY_DIR/icnd.service"
# Appliance-only drop-in for icnd.service that adds Requires=/After=/
# ConditionPathExists= against icn-appliance-firstboot.service. The base
# icnd.service from deploy/ is shared with native installs, so we layer
# the appliance-specific dependency via a drop-in instead of editing it.
ICND_DROPIN="$APPLIANCE_DIR/systemd/icnd.service.d/10-firstboot-gate.conf"

for f in "$FIRSTBOOT_SCRIPT" "$FIRSTBOOT_UNIT" "$ICND_SERVICE" "$ICND_DROPIN" "$APPLIANCE_MANIFEST_EXAMPLE"; do
    if [ ! -f "$f" ]; then
        err "Expected source file missing: $f"
        exit 7
    fi
done

# virt-customize the image
log "Running virt-customize on $OUT_IMAGE ..."
VIRT_CUSTOMIZE_ARGS=(
    -a "$OUT_IMAGE"
)
# The libguestfs appliance cannot resolve DNS names when the build host uses a
# local stub resolver (systemd-resolved on 127.0.0.53): virt-customize installs
# ITS OWN resolv.conf pointing at the user-net DNS (10.0.2.3) for the duration
# of each apt operation, and that forwarder dies against the host stub — so
# --install fails ("Temporary failure resolving 'deb.debian.org'") for any
# package not already present in the base, and writing the guest's resolv.conf
# cannot help. TCP through the user-net NAT works fine; only name resolution is
# broken. ICN_APPLIANCE_BUILD_DNS therefore names a resolver the BUILD HOST
# queries directly; the resolved mirror addresses are pinned into the guest's
# /etc/hosts for the build (tagged lines), and the pins are removed as the last
# customize step so the produced image is unchanged.
if [ -n "${ICN_APPLIANCE_BUILD_DNS:-}" ]; then
    if ! [[ "$ICN_APPLIANCE_BUILD_DNS" =~ ^[0-9]{1,3}(\.[0-9]{1,3}){3}$ ]]; then
        err "ICN_APPLIANCE_BUILD_DNS must be an IPv4 address (got: '$ICN_APPLIANCE_BUILD_DNS')"
        exit 7
    fi
    BUILD_PIN_HOSTS="deb.debian.org security.debian.org"
    for h in $BUILD_PIN_HOSTS; do
        pin_ip="$(dig +short A "$h" "@$ICN_APPLIANCE_BUILD_DNS" 2>/dev/null | grep -E '^[0-9]{1,3}(\.[0-9]{1,3}){3}$' | head -1)"
        if [ -z "$pin_ip" ]; then
            err "ICN_APPLIANCE_BUILD_DNS: could not resolve $h via $ICN_APPLIANCE_BUILD_DNS"
            exit 7
        fi
        log "Build DNS pin: $h -> $pin_ip (guest /etc/hosts, build-time only)"
        VIRT_CUSTOMIZE_ARGS+=(
            --run-command "printf '%s %s # icn-build-pin\n' '$pin_ip' '$h' >> /etc/hosts"
        )
    done
fi
VIRT_CUSTOMIZE_ARGS+=(
    --update
    --install "ca-certificates,curl,openssl,python3,systemd,sudo"

    --mkdir /etc/icn
    --mkdir /etc/icn/roles
    --mkdir /var/lib/icn
    --mkdir /var/log/icn
    --mkdir /usr/share/icn
    --mkdir /usr/share/icn/static

    --copy-in "$ICND_BIN:/usr/local/bin"
    --copy-in "$ICNCTL_BIN:/usr/local/bin"
    --run-command "chmod +x /usr/local/bin/icnd /usr/local/bin/icnctl"

    --copy-in "$ICND_SERVICE:/etc/systemd/system"
    --copy-in "$FIRSTBOOT_UNIT:/etc/systemd/system"

    # Appliance drop-in that gates icnd.service on firstboot success.
    --mkdir /etc/systemd/system/icnd.service.d
    --copy-in "$ICND_DROPIN:/etc/systemd/system/icnd.service.d"

    --copy-in "$FIRSTBOOT_SCRIPT:/usr/local/sbin"
    --run-command "chmod +x /usr/local/sbin/icn-appliance-firstboot.sh"
    --run-command "ln -sf /usr/local/sbin/icn-appliance-firstboot.sh /usr/local/sbin/icn-appliance-firstboot"

    --copy-in "$APPLIANCE_MANIFEST_EXAMPLE:/etc/icn"

    # Idempotent: skip useradd if the user already exists; let real failures
    # (missing useradd, FS error, etc.) surface as a non-zero exit instead of
    # being swallowed by `|| true`.
    --run-command "id -u icn >/dev/null 2>&1 || useradd --system --home-dir /var/lib/icn --shell /bin/false icn"
    --run-command "chown -R icn:icn /var/lib/icn /var/log/icn"

    --run-command "systemctl enable icn-appliance-firstboot.service"
    --run-command "systemctl enable icnd.service"
)
# Role examples (only if at least one matches the glob)
if [ -f "${ROLE_EXAMPLES[0]:-/nonexistent}" ]; then
    for r in "${ROLE_EXAMPLES[@]}"; do
        VIRT_CUSTOMIZE_ARGS+=( --copy-in "$r:/etc/icn/roles" )
    done
fi

# Optional health-check helper if the existing script is present
if [ -f "$HEALTH_CHECK_BIN" ]; then
    VIRT_CUSTOMIZE_ARGS+=(
        --copy-in "$HEALTH_CHECK_BIN:/usr/local/bin"
        --run-command "mv /usr/local/bin/$(basename "$HEALTH_CHECK_BIN") /usr/local/bin/icn-health-check"
        --run-command "chmod +x /usr/local/bin/icn-health-check"
    )
fi

# ---------- DEV/DEMO profile (ICN_APPLIANCE_DEMO_PROFILE=1) ----------
# Everything in this block is demo-only payload and configuration. None of
# it is installed on the base image, and the manifest records the choice
# (demo_profile: true). See deploy/appliance/README.md "Demo profile".
DEMO_STAGE=""
if [ "$DEMO_PROFILE" = "1" ]; then
    log "Demo profile requested: staging DEV/DEMO payload..."
    DEMO_SEED_SCRIPT="$APPLIANCE_DIR/scripts/icn-demo-seed.sh"
    DEMO_VERIFY_SCRIPT="$APPLIANCE_DIR/scripts/icn-demo-verify.sh"
    DEMO_RESET_SCRIPT="$APPLIANCE_DIR/scripts/icn-demo-reset.sh"
    DEMO_SESSION_SCRIPT="$APPLIANCE_DIR/scripts/icn-demo-session.py"
    DEMO_STATUS_SCRIPT="$APPLIANCE_DIR/scripts/icn-demo-status.sh"
    MEMBER_SHELL_UNIT="$APPLIANCE_DIR/systemd/icn-member-shell.service"
    DEMO_SESSION_UNIT="$APPLIANCE_DIR/systemd/icn-demo-session.service"
    DEMO_DROPIN="$APPLIANCE_DIR/systemd/icnd.service.d/20-demo-profile.conf"
    for f in "$DEMO_SEED_SCRIPT" "$DEMO_VERIFY_SCRIPT" "$DEMO_RESET_SCRIPT" \
             "$DEMO_SESSION_SCRIPT" "$DEMO_STATUS_SCRIPT" \
             "$MEMBER_SHELL_UNIT" "$DEMO_SESSION_UNIT" "$DEMO_DROPIN"; do
        if [ ! -f "$f" ]; then
            err "Demo profile source file missing: $f"
            exit 7
        fi
    done
    for d in "$REPO_ROOT/web/member-shell" "$REPO_ROOT/web/pilot-ui/fixtures" \
             "$REPO_ROOT/web/rehearsal-landing" \
             "$REPO_ROOT/institutions/nycn" "$REPO_ROOT/demo/nycn-dogfood"; do
        if [ ! -d "$d" ]; then
            err "Demo profile payload directory missing: $d"
            exit 7
        fi
    done
    for f in "$REPO_ROOT/scripts/local_receipt_chain_13of13_rehearsal.sh" \
             "$REPO_ROOT/scripts/local_economic_receipt_chain_demo.sh" \
             "$REPO_ROOT/scripts/rehearsal_pending_publish_evidence.py" \
             "$REPO_ROOT/web/member-shell/fixtures/pending-publish-summary.json" \
             "$REPO_ROOT/web/member-shell/fixtures/pending-publish-evidence-export.json" \
             "$REPO_ROOT/docs/scripts/validate-rehearsal-evidence.py"; do
        if [ ! -f "$f" ]; then
            err "Demo profile payload file missing: $f"
            exit 7
        fi
    done

    # Stage a directory tree so virt-customize --copy-in can install whole
    # directories with their relative layout preserved:
    #   static/web/{member-shell, pilot-ui/fixtures}   (shell's relative
    #       fixture fetch path "../pilot-ui/fixtures/..." must keep working)
    #   demo/institutions/nycn                          (fixture institution)
    #   demo/repo/{scripts, docs/scripts, docs/contracts, demo/nycn-dogfood}
    #       (the 13/13 wrapper resolves ROOT as dirname($0)/.., so the
    #        bundled copy must preserve the repo-relative layout)
    DEMO_STAGE="$ICN_APPLIANCE_OUTPUT_DIR/.demo-stage.$$"
    rm -rf "$DEMO_STAGE"
    mkdir -p \
        "$DEMO_STAGE/static/web/pilot-ui" \
        "$DEMO_STAGE/demo/institutions" \
        "$DEMO_STAGE/demo/repo/scripts" \
        "$DEMO_STAGE/demo/repo/docs/scripts" \
        "$DEMO_STAGE/demo/repo/web/member-shell/fixtures" \
        "$DEMO_STAGE/demo/repo/demo"
    cp -r "$REPO_ROOT/web/member-shell"            "$DEMO_STAGE/static/web/"
    cp -r "$REPO_ROOT/web/pilot-ui/fixtures"       "$DEMO_STAGE/static/web/pilot-ui/"
    cp -r "$REPO_ROOT/web/rehearsal-landing"       "$DEMO_STAGE/static/web/"
    # Non-secret build provenance for the landing page's status strip
    # (GET /build-info.json). The typed appliance manifest stays the artifact
    # of record; this is a display convenience staged next to the static tree.
    DEMO_GIT_COMMIT="$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null || echo unknown)"
    python3 - "$DEMO_STAGE/static/web/build-info.json" "$DEMO_GIT_COMMIT" \
        "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$ICN_APPLIANCE_VERSION" <<'PYEOF'
import json, sys
path, commit, ts, version = sys.argv[1:5]
with open(path, "w", encoding="utf-8") as f:
    json.dump({
        "git_commit": commit,
        "build_timestamp": ts,
        "image_version": version,
        "demo_profile": True,
        "non_production": True,
    }, f, indent=2)
PYEOF
    cp -r "$REPO_ROOT/institutions/nycn"           "$DEMO_STAGE/demo/institutions/"
    cp -r "$REPO_ROOT/demo/nycn-dogfood"           "$DEMO_STAGE/demo/repo/demo/"
    cp "$REPO_ROOT/scripts/local_receipt_chain_13of13_rehearsal.sh" \
       "$REPO_ROOT/scripts/local_economic_receipt_chain_demo.sh" \
       "$REPO_ROOT/scripts/rehearsal_pending_publish_evidence.py" \
       "$DEMO_STAGE/demo/repo/scripts/"
    cp "$REPO_ROOT/docs/scripts/validate-rehearsal-evidence.py" \
       "$DEMO_STAGE/demo/repo/docs/scripts/"
    # Fixtures the pending-publish evidence generator reads (icn-demo-verify
    # --pending-publish resolves ROOT as demo/repo, so co-locate them there).
    cp "$REPO_ROOT/web/member-shell/fixtures/pending-publish-summary.json" \
       "$REPO_ROOT/web/member-shell/fixtures/pending-publish-evidence-export.json" \
       "$DEMO_STAGE/demo/repo/web/member-shell/fixtures/"
    if [ -d "$REPO_ROOT/docs/contracts" ]; then
        cp -r "$REPO_ROOT/docs/contracts" "$DEMO_STAGE/demo/repo/docs/"
    fi

    VIRT_CUSTOMIZE_ARGS+=(
        --mkdir /usr/share/icn/demo
        --copy-in "$DEMO_STAGE/static/web:/usr/share/icn/static"
        --copy-in "$DEMO_STAGE/demo/institutions:/usr/share/icn/demo"
        --copy-in "$DEMO_STAGE/demo/repo:/usr/share/icn/demo"
        --copy-in "$MEMBER_SHELL_UNIT:/etc/systemd/system"
        --copy-in "$DEMO_SESSION_UNIT:/etc/systemd/system"
        --copy-in "$DEMO_DROPIN:/etc/systemd/system/icnd.service.d"
        --copy-in "$DEMO_SEED_SCRIPT:/usr/local/sbin"
        --copy-in "$DEMO_VERIFY_SCRIPT:/usr/local/sbin"
        --copy-in "$DEMO_RESET_SCRIPT:/usr/local/sbin"
        --copy-in "$DEMO_SESSION_SCRIPT:/usr/local/sbin"
        --copy-in "$DEMO_STATUS_SCRIPT:/usr/local/sbin"
        --run-command "chmod +x /usr/local/sbin/icn-demo-seed.sh /usr/local/sbin/icn-demo-verify.sh /usr/local/sbin/icn-demo-reset.sh /usr/local/sbin/icn-demo-session.py /usr/local/sbin/icn-demo-status.sh"
        --run-command "ln -sf /usr/local/sbin/icn-demo-seed.sh /usr/local/sbin/icn-demo-seed && ln -sf /usr/local/sbin/icn-demo-verify.sh /usr/local/sbin/icn-demo-verify && ln -sf /usr/local/sbin/icn-demo-reset.sh /usr/local/sbin/icn-demo-reset && ln -sf /usr/local/sbin/icn-demo-status.sh /usr/local/sbin/icn-demo-status"
        --run-command "systemctl enable icn-member-shell.service"
        --run-command "systemctl enable icn-demo-session.service"
        # The bundled 13/13 evidence validator (icn-demo-verify --chain)
        # needs the python3 jsonschema package. Debian genericcloud images
        # provide it transitively via cloud-init; assert it here so a base
        # image without it fails the BUILD with a clear message instead of
        # failing the advertised --chain path at demo time. (No apt install:
        # the libguestfs appliance cannot rely on network/DNS — see the
        # python3-not-jq note in the demo scripts.)
        --run-command "python3 -c \"import jsonschema\" || { echo \"ERROR: demo profile requires python3-jsonschema in the base image (Debian genericcloud ships it via cloud-init); this base image lacks it\" >&2; exit 1; }"
    )
fi

# ---------- LAN profile (ICN_APPLIANCE_LAN_PROFILE=1; DEMO profile required) ----
# Single-origin LAN serving: nginx inside the VM terminates ONE browser origin
# (ICN_APPLIANCE_LAN_ORIGIN) and forwards /v1/dev/demo/* to the loopback-only
# session endpoint (:8091, bind unchanged) and /v1/* to the gateway (:8080),
# while serving the landing page + member shell as static files — so every
# browser fetch is same-origin. The gateway CORS allowlist and the session
# endpoint's origin allowlist each gain EXACTLY this one origin via rendered
# drop-ins. Off by default; with the flag unset the image is byte-identical to
# a plain demo build. See deploy/appliance/lan/README.md.
LAN_PROFILE="${ICN_APPLIANCE_LAN_PROFILE:-0}"
LAN_STAGE=""
if [ "$LAN_PROFILE" = "1" ]; then
    if [ "$DEMO_PROFILE" != "1" ]; then
        err "LAN profile requires the demo profile (ICN_APPLIANCE_DEMO_PROFILE=1)"
        exit 7
    fi
    LAN_ORIGIN="${ICN_APPLIANCE_LAN_ORIGIN:-}"
    # Exact origin only: scheme://host[:port] — no path, no wildcard. The host
    # charset restriction also keeps the sed render below injection-free.
    if ! [[ "$LAN_ORIGIN" =~ ^https?://[A-Za-z0-9.-]+(:[0-9]{1,5})?$ ]]; then
        err "ICN_APPLIANCE_LAN_ORIGIN must be http(s)://host[:port] (got: '${LAN_ORIGIN:-unset}')"
        exit 7
    fi
    LAN_DIR="$APPLIANCE_DIR/lan"
    LAN_SCHEME="${LAN_ORIGIN%%://*}"
    LAN_HOST="${LAN_ORIGIN#*://}"; LAN_HOST="${LAN_HOST%%:*}"
    for f in "$LAN_DIR/nginx-icn-rehearsal-http.conf.in" \
             "$LAN_DIR/nginx-icn-rehearsal-https.conf.in" \
             "$LAN_DIR/icnd-30-lan-origin.conf.in" \
             "$LAN_DIR/icn-demo-session-30-lan-origin.conf.in"; do
        if [ ! -f "$f" ]; then
            err "LAN profile template missing: $f"
            exit 7
        fi
    done
    LAN_STAGE="$ICN_APPLIANCE_OUTPUT_DIR/.lan-stage.$$"
    rm -rf "$LAN_STAGE"
    mkdir -p "$LAN_STAGE/nginx" "$LAN_STAGE/icnd-dropin" "$LAN_STAGE/session-dropin" "$LAN_STAGE/tls"
    if [ "$LAN_SCHEME" = "https" ]; then
        NGINX_TEMPLATE="$LAN_DIR/nginx-icn-rehearsal-https.conf.in"
        LAN_TLS_CERT="${ICN_APPLIANCE_LAN_TLS_CERT:-}"
        LAN_TLS_KEY="${ICN_APPLIANCE_LAN_TLS_KEY:-}"
        if [ ! -f "$LAN_TLS_CERT" ] || [ ! -f "$LAN_TLS_KEY" ]; then
            err "https LAN origin requires ICN_APPLIANCE_LAN_TLS_CERT and ICN_APPLIANCE_LAN_TLS_KEY (operator-supplied, e.g. from an internal CA)"
            exit 7
        fi
        cp "$LAN_TLS_CERT" "$LAN_STAGE/tls/rehearsal.crt"
        cp "$LAN_TLS_KEY"  "$LAN_STAGE/tls/rehearsal.key"
        chmod 600 "$LAN_STAGE/tls/rehearsal.key"
    else
        NGINX_TEMPLATE="$LAN_DIR/nginx-icn-rehearsal-http.conf.in"
        warn "LAN origin is plain http — the bearer session travels unencrypted on the LAN; prefer an https origin with an internal-CA certificate."
    fi
    sed -e "s|@LAN_HOST@|$LAN_HOST|g" -e "s|@LAN_ORIGIN@|$LAN_ORIGIN|g" \
        "$NGINX_TEMPLATE" > "$LAN_STAGE/nginx/icn-rehearsal.conf"
    sed -e "s|@LAN_ORIGIN@|$LAN_ORIGIN|g" \
        "$LAN_DIR/icnd-30-lan-origin.conf.in" > "$LAN_STAGE/icnd-dropin/30-lan-origin.conf"
    sed -e "s|@LAN_ORIGIN@|$LAN_ORIGIN|g" \
        "$LAN_DIR/icn-demo-session-30-lan-origin.conf.in" > "$LAN_STAGE/session-dropin/30-lan-origin.conf"
    log "LAN profile: single origin $LAN_ORIGIN (nginx in-VM; session endpoint stays loopback)"
    VIRT_CUSTOMIZE_ARGS+=(
        # qemu-guest-agent: the LAN profile targets a long-lived VM on a real
        # hypervisor (not a throwaway user-net QEMU), where clean host-initiated
        # shutdown and agent-side diagnostics matter.
        --install nginx,qemu-guest-agent
        --run-command "systemctl enable qemu-guest-agent"
        --mkdir /etc/systemd/system/icn-demo-session.service.d
        --copy-in "$LAN_STAGE/nginx/icn-rehearsal.conf:/etc/nginx/sites-available"
        --run-command "ln -sf ../sites-available/icn-rehearsal.conf /etc/nginx/sites-enabled/icn-rehearsal.conf && rm -f /etc/nginx/sites-enabled/default"
        --copy-in "$LAN_STAGE/icnd-dropin/30-lan-origin.conf:/etc/systemd/system/icnd.service.d"
        --copy-in "$LAN_STAGE/session-dropin/30-lan-origin.conf:/etc/systemd/system/icn-demo-session.service.d"
        --write "/etc/icn/lan-profile.env:ICN_LAN_ORIGIN=$LAN_ORIGIN"
        --run-command "systemctl enable nginx"
    )
    if [ "$LAN_SCHEME" = "https" ]; then
        VIRT_CUSTOMIZE_ARGS+=(
            --mkdir /etc/icn/tls
            --copy-in "$LAN_STAGE/tls/rehearsal.crt:/etc/icn/tls"
            --copy-in "$LAN_STAGE/tls/rehearsal.key:/etc/icn/tls"
            --run-command "chown root:root /etc/icn/tls/rehearsal.key && chmod 600 /etc/icn/tls/rehearsal.key"
        )
    fi
fi

# Remove the build-time mirror pins (see ICN_APPLIANCE_BUILD_DNS above) so the
# produced image's /etc/hosts is unchanged.
if [ -n "${ICN_APPLIANCE_BUILD_DNS:-}" ]; then
    VIRT_CUSTOMIZE_ARGS+=(
        --run-command "sed -i '/# icn-build-pin\$/d' /etc/hosts"
    )
fi

virt-customize "${VIRT_CUSTOMIZE_ARGS[@]}"

if [ -n "$DEMO_STAGE" ]; then
    rm -rf "$DEMO_STAGE"
fi
if [ -n "$LAN_STAGE" ]; then
    rm -rf "$LAN_STAGE"
fi

# virt-sysprep to scrub instance-specific state. --operations chosen
# narrowly so we don't accidentally wipe what we just installed.
log "Running virt-sysprep (machine-id, logfiles, bash-history, tmp-files)..."
virt-sysprep -a "$OUT_IMAGE" \
    --operations machine-id,logfiles,bash-history,tmp-files

# Final hash + typed manifest (emit + verify)
log "Hashing output image..."
OUT_SHA256="$(sha256sum "$OUT_IMAGE" | awk '{print $1}')"

GIT_COMMIT="$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null || echo unknown)"
BUILD_TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# ---------- typed appliance build manifest (emit + verify) ----------
# Replaces the former ad-hoc JSON heredoc with the Rust-owned manifest emitter
# (`icnctl appliance emit-manifest`, PR #2259). icnctl streams SHA-256 over the
# image, the base image, and each built binary itself, and writes a typed
# `icn_appliance::ApplianceManifest`. That schema uses `deny_unknown_fields`, so
# the old free-form "notes" array is intentionally dropped — the human
# explanation now lives in this script's logs and in deploy/appliance/README.md,
# not in the manifest payload.
#
# Posture: no --production / --signed / --immutable, so the manifest records the
# honest dev posture (non_production=true, signed=false, immutable=false).
# --demo-profile is passed only when ICN_APPLIANCE_DEMO_PROFILE=1, matching the
# payload actually installed above. The image stays an unsigned, mutable, local
# dev artifact — not production, not reproducible, not partner-distributable.
#
# base_image_sha256 is now the ACTUAL hash of the staged base image. This is a
# deliberate tightening: the old heredoc recorded "unset" when the optional
# ICN_APPLIANCE_BASE_SHA256 env var was absent. That env var still gates the
# pre-build base-image checksum verification above; it no longer feeds the
# manifest.
#
# Paths: --image and --base-image are absolutized so the recorded image_path /
# base_image_path are root-independent. The binary SOURCE labels stay
# repo-relative (icn/target/release/...), so verify-manifest runs with
# --root "$REPO_ROOT" to resolve them. A single root satisfies both: absolute
# image/base paths ignore it, and the repo-relative binary sources resolve under
# it. (verify-manifest hashes the binaries' SOURCE under --root, so the source
# label and the just-built binary at $REPO_ROOT/icn/target/release/<bin> must
# refer to the same file — they do.)
log "Emitting typed appliance manifest: $OUT_MANIFEST"
OUT_IMAGE_ABS="$(cd "$(dirname "$OUT_IMAGE")" && pwd)/$(basename "$OUT_IMAGE")"
BASE_IMAGE_ABS="$(cd "$(dirname "$ICN_APPLIANCE_BASE_IMAGE")" && pwd)/$(basename "$ICN_APPLIANCE_BASE_IMAGE")"

EMIT_ARGS=(
    --appliance-id "icn-appliance-dev"
    --image-version "$ICN_APPLIANCE_VERSION"
    --arch "$ARCH"
    --image-format "$IMAGE_FORMAT"
    --image "$OUT_IMAGE_ABS"
    --base-image "$BASE_IMAGE_ABS"
    --git-commit "$GIT_COMMIT"
    --build-timestamp "$BUILD_TS"
    --binary "/usr/local/bin/icnd=icn/target/release/icnd=$ICND_BIN"
    --binary "/usr/local/bin/icnctl=icn/target/release/icnctl=$ICNCTL_BIN"
    --output "$OUT_MANIFEST"
)
# Demo images carry extra DEV/DEMO payload; record that in the manifest so the
# posture is never misread as a clean base image.
if [ "$DEMO_PROFILE" = "1" ]; then
    EMIT_ARGS+=( --demo-profile )
fi

# emit-manifest and verify-manifest run under `set -e`: a non-zero exit from
# either (hash failure, missing artifact, hash mismatch, posture contradiction)
# aborts the build instead of leaving a half-described or unverified image.
"$ICNCTL_BIN" appliance emit-manifest "${EMIT_ARGS[@]}"

# Re-verify what we just emitted with the fail-closed verifier (PR #2260):
# re-hash image + base + each binary and re-check posture, rooted at the repo
# so the repo-relative binary SOURCE labels resolve to the built binaries.
log "Verifying emitted manifest (fail-closed re-hash): $OUT_MANIFEST"
"$ICNCTL_BIN" appliance verify-manifest "$OUT_MANIFEST" --root "$REPO_ROOT"

log "DONE."
log "  Image:    $OUT_IMAGE"
log "  SHA256:   $OUT_SHA256"
log "  Manifest: $OUT_MANIFEST"
echo
log "Next: boot with deploy/appliance/smoke/smoke-local.sh --real"
log "      ICN_APPLIANCE_IMAGE=$OUT_IMAGE ICN_APPLIANCE_SSH_KEY=... bash deploy/appliance/smoke/smoke-local.sh --real"
